# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-11 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turbine', '0068_auto_20190909_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Rotor Blade Inspection', 'Rotor Blade Inspection'), ('Electrical Inspection', 'Electrical Inspection'), ('Videoendoscopic Gearbox Inspection', 'Videoendoscopic Gearbox Inspection'), ('Service Lift Inspection by Certified Body', 'Service Lift Inspection by Certified Body'), ('Safety Equipment Inspection', 'Safety Equipment Inspection')], max_length=50)),
                ('every_count', models.PositiveIntegerField(verbose_name='Every')),
                ('time_interval', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], max_length=10)),
                ('for_count', models.PositiveIntegerField(verbose_name='For')),
                ('duration', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], max_length=10)),
                ('done', models.DateField(blank=True, null=True)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine')),
            ],
        ),
    ]
