# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-11 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='done',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 6, 51, 8, 940109), verbose_name='First Performance'),
        ),
    ]
