# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190911_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='done',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='First Performance'),
        ),
    ]
