# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190911_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='done',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Erste Durchführung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[('Jahr', 'Jahr'), ('Monat', 'Monat'), ('Tag', 'Tag')], max_length=10, verbose_name='Dauer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='every_count',
            field=models.PositiveIntegerField(verbose_name='Alle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='for_count',
            field=models.PositiveIntegerField(verbose_name='für'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_interval',
            field=models.CharField(choices=[('Jahr', 'Jahr'), ('Monat', 'Monat'), ('Tag', 'Tag')], max_length=10, verbose_name='Zeitintervall'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('WKP', 'WKP'), ('ZOP', 'ZOP'), ('Getriebeendoskopie', 'Getriebeendoskopie'), ('Rotorblattgutachten', 'Rotorblattgutachten'), ('Sicherheitsüberprüfung', 'Sicherheitsüberprüfung'), ('BFA Wartung', 'BFA Wartung'), ('ZÜS BFA', 'ZÜS BFA'), ('Generalüberholung Winde', 'Generalüberholung Winde'), ('GÜ / Austausch Bordkran', 'GÜ / Austausch Bordkran'), ('Gittermastprüfung', 'Gittermastprüfung'), ('DGUV V3', 'DGUV V3')], max_length=50, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine', verbose_name='WEA'),
        ),
    ]
