# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190912_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_turbine', to='turbine.Turbine', verbose_name='WEA'),
        ),
    ]
