# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190918_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[('Jahre', 'Jahre'), ('Monate', 'Monate'), ('Tage', 'Tage')], max_length=10, verbose_name='Dauer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_interval',
            field=models.CharField(choices=[('Jahre', 'Jahre'), ('Monate', 'Monate'), ('Tage', 'Tage')], max_length=10, verbose_name='Zeitintervall'),
        ),
    ]
