# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190924_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='date',
            name='execution_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Datum (ist)'),
        ),
        migrations.AlterField(
            model_name='date',
            name='part_of_contract',
            field=models.CharField(blank=True, choices=[('Ja', 'Ja'), ('Nein', 'Nein'), ('zustandsorientiert', 'zustandsorientiert'), ('einmalig', 'einmalig')], max_length=20, null=True, verbose_name='Vertragsbestandteil'),
        ),
        migrations.AlterField(
            model_name='date',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='Dienstleister'),
        ),
    ]
