# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191002_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.CharField(choices=[('ausstehend', 'ausstehend'), ('geplant', 'geplant'), ('abgeschlossen', 'abgeschlossen')], max_length=15),
        ),
    ]
