# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0068_auto_20190909_1305'),
        ('events', '0012_event_turbines'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='turbine',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, related_name='date_turbine', to='turbine.Turbine', verbose_name='WEA'),
            preserve_default=False,
        ),
    ]
