# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-14 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_turbine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum (ist)'),
        ),
    ]
