# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20191014_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.CharField(choices=[('ausstehend', 'ausstehend'), ('eingeplant/terminiert', 'eingeplant/terminiert'), ('angemeldet', 'angemeldet'), ('durchgeführt', 'durchgeführt'), ('Bericht erhalten', 'Bericht erhalten'), ('Rechnung erhalten', 'Rechnung erhalten'), ('Vorgang schließen', 'Vorgang schließen')], max_length=15),
        ),
    ]
