# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20191107_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Plandatum'),
        ),
        migrations.AlterField(
            model_name='date',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prüfdatum'),
        ),
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.CharField(choices=[('ausstehend', 'ausstehend'), ('beauftragt', 'beauftragt'), ('angemeldet', 'angemeldet'), ('durchgeführt', 'durchgeführt'), ('Bericht erhalten', 'Bericht erhalten'), ('Rechnung erhalten', 'Rechnung erhalten')], max_length=25),
        ),
    ]
