# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20191115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='done',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Solldatum Erste Durchführung'),
        ),
    ]
