# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20191115_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.CharField(choices=[('ausstehend', 'ausstehend'), ('beauftragt', 'beauftragt'), ('angemeldet', 'angemeldet'), ('durchgeführt', 'durchgeführt'), ('Bericht erhalten', 'Bericht erhalten'), ('Rechnung erhalten', 'Rechnung erhalten'), ('abgeschlossen', 'abgeschlossen')], max_length=25),
        ),
    ]
