# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-04 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200204_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='date_de',
        ),
        migrations.RemoveField(
            model_name='date',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='date',
            name='execution_date_de',
        ),
        migrations.RemoveField(
            model_name='date',
            name='execution_date_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='done_de',
        ),
        migrations.RemoveField(
            model_name='event',
            name='done_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='every_count_de',
        ),
        migrations.RemoveField(
            model_name='event',
            name='every_count_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='for_count_de',
        ),
        migrations.RemoveField(
            model_name='event',
            name='for_count_en',
        ),
    ]
