# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-07 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_auto_20200204_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responsibles',
            field=models.ManyToManyField(help_text='Who is responsible?', related_name='responsibles_for_event', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
    ]
