# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_event_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='status',
            field=models.CharField(choices=[('remaining', 'remaining'), ('ordered', 'ordered'), ('scheduled', 'scheduled'), ('executed', 'executed'), ('confirmed', 'confirmed'), ('report received', 'report received'), ('invoice received', 'invoice received'), ('closed', 'closed')], max_length=25),
        ),
        migrations.AlterField(
            model_name='date',
            name='status_de',
            field=models.CharField(choices=[('remaining', 'remaining'), ('ordered', 'ordered'), ('scheduled', 'scheduled'), ('executed', 'executed'), ('confirmed', 'confirmed'), ('report received', 'report received'), ('invoice received', 'invoice received'), ('closed', 'closed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='status_en',
            field=models.CharField(choices=[('remaining', 'remaining'), ('ordered', 'ordered'), ('scheduled', 'scheduled'), ('executed', 'executed'), ('confirmed', 'confirmed'), ('report received', 'report received'), ('invoice received', 'invoice received'), ('closed', 'closed')], max_length=25, null=True),
        ),
    ]
