# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200320_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='part_of_contract_de',
        ),
        migrations.RemoveField(
            model_name='date',
            name='part_of_contract_en',
        ),
        migrations.AddField(
            model_name='event',
            name='part_of_contract',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('condition based', 'condition based'), ('non-recurrent', 'non-recurrent')], max_length=20, null=True, verbose_name='Part of Contract'),
        ),
        migrations.AddField(
            model_name='event',
            name='part_of_contract_de',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('condition based', 'condition based'), ('non-recurrent', 'non-recurrent')], max_length=20, null=True, verbose_name='Part of Contract'),
        ),
        migrations.AddField(
            model_name='event',
            name='part_of_contract_en',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('condition based', 'condition based'), ('non-recurrent', 'non-recurrent')], max_length=20, null=True, verbose_name='Part of Contract'),
        ),
    ]
