# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20200320_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='part_of_contract',
        ),
        migrations.AddField(
            model_name='date',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
    ]
