# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20200703_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('Recurring inspection', 'Recurring inspection'), ('Condition based inspection', 'Condition based inspection'), ('Gearbox endoscopic inspection', 'Gearbox endoscopic inspection'), ('Rotor blade inspection', 'Rotor blade inspection'), ('Safety inspection', 'Safety inspection'), ('Service lift maintenance', 'Service lift maintenance'), ('ZÜS service lift', 'ZÜS service lift'), ('General Overhaul Winch', 'General Overhaul Winch'), ('General Overhaul Deck Crane', 'General Overhaul Deck Crane'), ('Lattice tower inspection', 'Lattice tower maintenance'), ('DGUV V3 WEC', 'DGUV V3 WEC'), ('DGUV V3 substation', 'DGUV V3 substation'), ('Maintenance of Substation', 'Maintenance of Substation'), ('Overcurrent Protection Inspection WEC', 'Overcurrent Protection Inspection WEC'), ('Overcurrent Protection Inspection Substation', 'Overcurrent Protection Inspection Substation'), ('Inspection of pressure vessel', 'Inspection of pressure vessel'), ('Further official obligation', 'Further official obligation')], max_length=50, verbose_name='Type'),
        ),
    ]
