# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wind_farms', '0054_auto_20180503_0132'),
        ('polls', '0038_auto_20180514_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Coffee', 'Coffee'), ('Soft Offer', 'Soft Offer'), ('Hard Offer', 'Hard Offer'), ('Negotiation', 'Negotiation'), ('Final Negotiation', 'Final Negotiation'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], default='Coffee', max_length=25)),
                ('prob', models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, null=True, verbose_name='Probability [%]')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('manufacturer', models.ManyToManyField(db_index=True, related_name='project_wec_manufacturers', to='polls.Manufacturer', verbose_name='Manufacturer')),
                ('wec_type', models.ManyToManyField(db_index=True, to='polls.WEC_Typ', verbose_name='WTG Type')),
                ('wind_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wind_farms.WindFarm')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together=set([('id', 'slug')]),
        ),
    ]
