# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0013_auto_20180503_0123'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wec_type',
        ),
        migrations.AddField(
            model_name='project',
            name='turbines',
            field=models.ManyToManyField(db_index=True, related_name='project_turbines', to='turbine.Turbine', verbose_name='Turbines'),
        ),
    ]
