# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180515_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_customer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30),
        ),
    ]
