# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_person'),
        ('projects', '0006_project_new_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Person'),
        ),
    ]
