# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_contact',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_operation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
