# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180516_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_signature',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
