# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_person_phone2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20180517_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Coffee', 'Coffee'), ('Soft Offer', 'Soft Offer'), ('Hard Offer', 'Hard Offer'), ('Negotiation', 'Negotiation'), ('Final Negotiation', 'Final Negotiation'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], default='Coffee', max_length=25)),
                ('prob', models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, null=True, verbose_name='Probability [%]')),
                ('new_customer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30)),
                ('last_contact', models.DateField(default=django.utils.timezone.now)),
                ('contract_type', models.CharField(choices=[('Contract Overview', 'Contract Overview'), ('Basic', 'Basic'), ('VWoGK', 'VWoGK'), ('VWmGKoR', 'VWmGKoR'), ('VWmGK', 'VWmGK'), ('Tender', 'Tender'), ('Remote Control', 'Remote Control'), ('TO', 'TO'), ('Spare Parts', 'Spare Parts'), ('Main Components', 'Main Components'), ('Support', 'Support'), ('Site Optimization', 'Site Optimization')], default='Contract Overview', max_length=30)),
                ('run_time', models.IntegerField(blank=True, default=5, null=True, verbose_name='Runtime [years]')),
                ('department', models.CharField(choices=[('Service', 'Service'), ('Technical Operations', 'Technical Operations'), ('Remote Control', 'Remote Control')], default='Service', max_length=20)),
                ('responsible', models.CharField(blank=True, max_length=20, null=True)),
                ('request_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_operation', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contract_signature', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price', models.IntegerField(blank=True, default=35000, null=True, verbose_name='Price [€/WTG/year]')),
                ('ebt', models.IntegerField(blank=True, default=350000, null=True, verbose_name='EBT [€]')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='player.Player')),
                ('customer_contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='player.Person')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical project',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='changed_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
