# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_comment_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
