# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-25 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
    ]
