# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_dwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('Contract Overview', 'Contract Overview'), ('Basic', 'Basic'), ('Vario', 'Vario'), ('Vario+', 'Vario+'), ('VWoGK', 'VWoGK'), ('VWmGKoR', 'VWmGKoR'), ('VWmGK', 'VWmGK'), ('Tender', 'Tender'), ('Remote Control', 'Remote Control'), ('TO', 'TO'), ('Spare Parts', 'Spare Parts'), ('Main Components', 'Main Components'), ('Support', 'Support'), ('Site Optimization', 'Site Optimization')], default='Contract Overview', max_length=30),
        ),
    ]
