# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180530_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without MC', 'Full Maintenance without MC'), ('Full Maintenance with MC', 'Full Maintenance with MC'), ('Extension', 'Extension'), ('Extension without MC', 'Extension without MC'), ('Extension with MC', 'Extension with MC'), ('Spare Parts', 'Spare Parts'), ('Other', 'Other')], default='Contract Overview', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
