# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20180605_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/%Y/%m/%d/'),
        ),
    ]
