# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-27 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20180625_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_customer', to='player.Player'),
        ),
    ]
