# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180627_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',), 'permissions': (('has_sales_status', 'Can create and edit Sales projects.'),)},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Potential', 'Potential'), ('Coffee', 'Coffee'), ('Soft Offer', 'Soft Offer'), ('Hard Offer', 'Hard Offer'), ('Negotiation', 'Negotiation'), ('Final Negotiation', 'Final Negotiation'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], default='Coffee', max_length=25),
        ),
    ]
