# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-20 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20180815_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_projects', to='player.Person'),
        ),
    ]
