# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-29 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20180820_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_contact',
        ),
    ]
