# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_project_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_signature',
            field=models.DateField(blank=True, help_text='When is the contract intended to be signed?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(help_text='Which company are we in touch with?', on_delete=django.db.models.deletion.CASCADE, related_name='project_customer', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, help_text="Who is the customer's contact person?", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_projects', to='player.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', help_text='Which unit is responsible for this project?', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='ebt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Which margin results from the price?', max_digits=4, null=True, verbose_name='EBT [%]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='new_customer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Is the customer new?', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, help_text='State the average yearly remuneration per WTG', null=True, verbose_name='Price [€/WTG/year]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prob',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimate the probability of conclusion', max_digits=5, null=True, verbose_name='Probability [%]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was the first contact established?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='run_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Runtime [years]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_manager',
            field=models.ForeignKey(help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_operation',
            field=models.DateField(blank=True, help_text=' What is the intended contract commencement date?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='turbines',
            field=models.ManyToManyField(db_index=True, help_text='Assign all turbines related to this project', related_name='project_turbines', to='turbine.Turbine', verbose_name='Turbines'),
        ),
    ]
