# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20180912_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, help_text='State the average yearly remuneration per WTG', null=True, verbose_name='Price'),
        ),
    ]
