# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0044_auto_20180912_1139'),
        ('projects', '0033_auto_20180912_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologieverantwortlicher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='polls.Manufacturer')),
                ('technology_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
