# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_technologieverantwortlicher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('Service', 'Service'), ('Technical Operations', 'Technical Operations')], default='Service', max_length=20),
        ),
    ]
