# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20180930_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', help_text='Which unit is responsible for the service for this project?', max_length=30),
        ),
    ]
