# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_offer_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='offer_nr',
            field=models.CharField(help_text='Offer Number (online valid for DWTS)', max_length=50),
        ),
    ]
