# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20181126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='offer_nr',
            field=models.CharField(blank=True, help_text='Offer Number (online valid for DWTS)', max_length=50, null=True),
        ),
    ]
