# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20181203_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='new_customer',
        ),
    ]
