# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0059_auto_20181030_0942'),
        ('projects', '0042_remove_project_new_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation_Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='calculation_tool/%Y/%m/%d/')),
                ('version', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid_for_country', models.ManyToManyField(to='wind_farms.Country')),
            ],
        ),
    ]
