# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_calculation_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without MC', 'Full Maintenance without MC'), ('Full Maintenance with MC', 'Full Maintenance with MC'), ('Remote Control', 'Remote Control'), ('Spare Parts', 'Spare Parts'), ('Technical Operation', 'Technical Operation'), ('Other', 'Other')], default='Contract Overview', max_length=30),
        ),
    ]
