# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0047_auto_20180930_1740'),
        ('projects', '0044_auto_20190108_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('wind_farm', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, help_text='Additional information')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_number_created_by', to=settings.AUTH_USER_MODEL)),
                ('sales_manager', models.ForeignKey(help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wec_typ', models.ForeignKey(help_text='Enter the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Model')),
            ],
        ),
    ]
