# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20190212_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='offer_number',
        ),
    ]
