# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_remove_project_offer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='offer_number',
            field=models.ForeignKey(blank=True, help_text='Offer Number (online valid for DWTS)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.OfferNumber'),
        ),
    ]
