# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20190213_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offernumber',
            options={'get_latest_by': 'created'},
        ),
    ]
