# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20190213_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offernumber',
            name='number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
