# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20190213_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offernumber',
            name='wec_typ',
            field=models.ForeignKey(blank=True, help_text='Enter the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Model'),
        ),
    ]
