# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0053_auto_20190213_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offernumber',
            name='sales_manager',
        ),
        migrations.AddField(
            model_name='offernumber',
            name='sales_manager',
            field=models.ManyToManyField(help_text='Who is the responsible Sales Manager?', to=settings.AUTH_USER_MODEL),
        ),
    ]
