# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20180930_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0054_auto_20190213_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offernumber',
            name='sales_manager',
        ),
        migrations.AddField(
            model_name='offernumber',
            name='sales_manager',
            field=models.ForeignKey(default=7, help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='offernumber',
            name='wec_typ',
        ),
        migrations.AddField(
            model_name='offernumber',
            name='wec_typ',
            field=models.ManyToManyField(blank=True, help_text='Enter the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', null=True, to='polls.WEC_Typ', verbose_name='Model'),
        ),
    ]
