# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20190213_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(help_text='Which company are we in touch with?', on_delete=django.db.models.deletion.CASCADE, related_name='project_customer', to='player.Player', verbose_name='Negotiation Partner'),
        ),
    ]
