# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-19 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20190219_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offernumber',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
    ]
