# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20190219_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, help_text='Who is the contact person at the negetiotions partner?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_projects', to='player.Person', verbose_name='Contact Person'),
        ),
    ]
