# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-07 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20190219_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',), 'permissions': (('has_sales_status', 'Can create and edit Sales projects.'), ('can_create_project_overview', 'Can create an overview of sales projects'), ('can_create_custom_export', 'Can create a custom export of sales projects'))},
        ),
    ]
