# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20190307_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='awarding_reason',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Contract Design', 'Contract Design'), ('Experience with DWT', 'Experience with DWT'), ('Readiness', 'Readiness'), ('Regional Structures', 'Regional Structures'), ('Political Decision', 'Political Decision')], help_text='Which reason lead to the awarding of the contract?', max_length=30, null=True),
        ),
    ]
