# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-12 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0068_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recipient',
            field=models.ForeignKey(default=7, help_text='Who is the reminder for?', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(help_text='The reminder is going to pop up on this specified date, which has to be in the future.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='text',
            field=models.TextField(help_text='This text is going to appear in a mail which is going to be send on the the specified date to the recipient.'),
        ),
    ]
