# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20190322_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='offernumber',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTS', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', help_text='Which unit will this project be contracted to?', max_length=30),
        ),
    ]
