# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0038_auto_20190307_0939'),
        ('projects', '0072_auto_20190329_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('request_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was the first contact established?', null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('changed_by', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='pool_changed_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Which company are we in touch with?', on_delete=django.db.models.deletion.CASCADE, related_name='pool_customer', to='player.Player', verbose_name='Negotiation Partner')),
                ('customer_contact', models.ForeignKey(blank=True, help_text='Who is the contact person at the negetiotion partner?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_pool', to='player.Person', verbose_name='Contact Person')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, help_text='Who is the contact person at the negetiotion partner?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact_projects', to='player.Person', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='poolproject',
            name='projects',
            field=models.ManyToManyField(db_index=True, help_text='Assign all projects related to this Pool Project', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='poolproject',
            name='sales_manager',
            field=models.ForeignKey(help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, related_name='pool_sales_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='poolproject',
            index_together=set([('id', 'slug')]),
        ),
    ]
