# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20190402_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolproject',
            name='projects',
            field=models.ManyToManyField(db_index=True, help_text='Assign all projects related to this Pool Project', related_name='pool_projects', to='projects.Project'),
        ),
    ]
