# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20190402_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='offer_number',
            field=models.ForeignKey(blank=True, help_text='Offer Number to establish a connection to written offers', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.OfferNumber'),
        ),
    ]
