# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-09 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0075_auto_20190507_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='multiple_recipients',
            field=models.ManyToManyField(help_text='Who is the reminder addressed to?', related_name='reminder_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
    ]
