# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-23 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_auto_20190716_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='recipient',
        ),
    ]
