# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20190909_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without MC', 'Full Maintenance without MC'), ('Full Maintenance with MC', 'Full Maintenance with MC'), ('Remote Control', 'Remote Control'), ('Spare Parts', 'Spare Parts'), ('Technical Operation', 'Technical Operation'), ('Foundation works', 'Foundation works'), ('Subsea Foundation and Seabed works', 'Subsea Foundation and Seabed works'), ('Offshore sub station service', 'Offshore sub station service'), ('BNK', 'BNK'), ('Other', 'Other')], default='Contract Overview', max_length=30),
        ),
    ]
