# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-27 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created',)},
        ),
    ]
