# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_auto_20191127_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gearbox_endoscopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='rotor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='zop',
            field=models.BooleanField(default=False),
        ),
    ]
