# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20191218_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('Servicevertrag', 'Servicevertrag'), ('TBF-Vertrag', 'TBF-Vertrag'), ('Auftragsarbeiten', 'Auftragsarbeiten'), ('Materialanfrage', 'Materialanfrage'), ('Support-Vertrag', 'Support-Vertrag')], default='Servicevertrag', max_length=20)),
                ('wind_farm_name', models.CharField(max_length=50)),
                ('street_nr', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, help_text='Please specify ONE city', max_length=80)),
                ('location_details', models.CharField(max_length=200)),
                ('amount_wec', models.IntegerField()),
            ],
        ),
    ]
