# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_customerquestionnaire_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='wind_farm_name',
            field=models.CharField(help_text='If multiple names exists, please provide them all', max_length=50),
        ),
    ]
