# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20200121_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='contractual_partner',
            field=models.CharField(default='Deutsche Windtechnik', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_city',
            field=models.CharField(default='Osnabrück', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_contact_person',
            field=models.CharField(default='Max Mustermann', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_legal_form',
            field=models.CharField(default='GmbH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_mail',
            field=models.EmailField(default='info@deutsche-windtechnik.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+49541380538100', help_text="Format: '+49 541 38 05 38 100'", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_postal_code',
            field=models.CharField(default='49086', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='cp_street_nr',
            field=models.CharField(default='Heideweg 2-4', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='city',
            field=models.CharField(help_text='Please specify the city where the wind farm is located', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
    ]
