# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_auto_20200123_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='invoice_recipient',
            field=models.CharField(default='Deutsche Windtechnik', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_city',
            field=models.CharField(default='Osnabrück', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_contact_person',
            field=models.CharField(default='Max Mustermann', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_invoice_mail',
            field=models.EmailField(default='info@deutsche-windtechnik.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_mail',
            field=models.EmailField(default='info@deutsche-windtechnik.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+49 451 38 05 38 100', help_text="Format: '+49 541 38 05 38 100'", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_postal_code',
            field=models.CharField(default='49086', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_street_nr',
            field=models.CharField(default='Heideweg 2-4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ir_tax_id',
            field=models.CharField(default='123/456/789', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='location_details',
            field=models.CharField(blank=True, help_text='You can provide additional information', max_length=200),
        ),
    ]
