# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_auto_20200117_1125'),
        ('projects', '0092_auto_20200124_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine_CustomerQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbine_id', models.CharField(max_length=25)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer')),
                ('turbine_model', models.ForeignKey(help_text='Enter the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ')),
            ],
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='bank_institute',
            field=models.CharField(default='Sparkasse', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='bic',
            field=models.CharField(default='GENODEF', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='iban',
            field=models.CharField(default='DE3823456789012345', max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='sa_city',
            field=models.CharField(default='Osnabrück', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='sa_company',
            field=models.CharField(default='Deutsche Windtechnik', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='sa_information',
            field=models.CharField(default='More information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='sa_postal_code',
            field=models.CharField(default='49086', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='sa_street_nr',
            field=models.CharField(default='Heideweg 2-4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='vat_nr',
            field=models.CharField(default='123456789', max_length=50),
            preserve_default=False,
        ),
    ]
