# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-27 07:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20200126_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='comissioning',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 7, 11, 10, 789357, tzinfo=utc), help_text='Date of comissioning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='control_system',
            field=models.CharField(default='Bachmann', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='hub_height',
            field=models.DecimalField(decimal_places=1, default=100.5, help_text='Hub height in meters', max_digits=5),
            preserve_default=False,
        ),
    ]
