# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-31 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_auto_20200127_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tender',
            field=models.BooleanField(default=False, help_text='Is this project part of a tender?'),
        ),
    ]
