# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_project_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='turbine_id',
            field=models.CharField(help_text='Please provide the Turbine ID. If unknown, use this scheme: WindfarmName01.', max_length=25),
        ),
    ]
