# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_auto_20200220_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer'),
        ),
    ]
