# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_auto_20200228_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='contact_company',
            field=models.CharField(default='Deutsche Windtechnik', help_text='Please specify the company you work for', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='contact_name',
            field=models.CharField(default='Max Mustermann', help_text='Please enter your first and last name', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='contact_position',
            field=models.CharField(default='Geschäftsführer', help_text='Please specify your position within your company', max_length=80),
            preserve_default=False,
        ),
    ]
