# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_auto_20200306_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='hub_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hub height in meters', max_digits=5, null=True),
        ),
    ]
