# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_auto_20200306_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='comissioning',
            field=models.DateField(blank=True, help_text='Date of comissioning', null=True),
        ),
    ]
