# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_auto_20200306_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='contact_mail',
            field=models.EmailField(default='info-dwtx@deutsche-windtechnik.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='amount_wec',
            field=models.IntegerField(help_text='Please provide the number of concerned turbines', null=True),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_position',
            field=models.CharField(blank=True, help_text='Please specify your position within your company', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='wind_farm_name',
            field=models.CharField(help_text='If multiple names exists, please provide them all', max_length=80),
        ),
    ]
