# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_auto_20200308_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='customer_questionnaire',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='projects.CustomerQuestionnaire'),
            preserve_default=False,
        ),
    ]
