# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0106_turbine_customerquestionnaire_customer_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='cms',
            field=models.BooleanField(default='No', help_text='Is a CMS system installed?'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='flicker_detection',
            field=models.BooleanField(default='No', help_text='Is a shadow-model', verbose_name='Flicker detection system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='ice_sensor',
            field=models.BooleanField(default='No', help_text='Is an ice sensor installed?', verbose_name='Ice sensor'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_system',
            field=models.BooleanField(default='No', help_text='Is a obstacle light system installed', verbose_name='Obstacle light system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='tower_type',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], default='Tubular Tower', help_text='Type of tower', max_length=20, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='comissioning',
            field=models.DateField(blank=True, help_text='When was the WEC comissioned?', null=True, verbose_name='Date of comissioning'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='control_system',
            field=models.CharField(blank=True, help_text='Which control system is installed?', max_length=30, verbose_name='Control system'),
        ),
    ]
