# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_auto_20200312_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_de',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], default='Tubular Tower', help_text='Type of tower', max_length=20, null=True, verbose_name='Type of tower'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_en',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], default='Tubular Tower', help_text='Type of tower', max_length=20, null=True, verbose_name='Type of tower'),
        ),
    ]
