# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_auto_20200314_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please select one suitable option', max_length=20, verbose_name='Desired Scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope_de',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please select one suitable option', max_length=20, null=True, verbose_name='Desired Scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope_en',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please select one suitable option', max_length=20, null=True, verbose_name='Desired Scope'),
        ),
    ]
