# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_auto_20200320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='cms',
            field=models.BooleanField(default=False, help_text='Is a CMS system installed?'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='flicker_detection',
            field=models.BooleanField(default=False, help_text='Is a flicker detection module installed?', verbose_name='Flicker detection system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='ice_sensor',
            field=models.BooleanField(default=False, help_text='Is an ice sensor installed?', verbose_name='Ice sensor'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Chosse the manufacturer of the turbine', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_system',
            field=models.BooleanField(default=False, help_text='Is a obstacle light system installed?', verbose_name='Obstacle light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='turbine_id',
            field=models.CharField(blank=True, help_text='Please provide the Turbine ID.', max_length=25, verbose_name='Turbine ID'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='turbine_model',
            field=models.ForeignKey(blank=True, help_text='Choose the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Turbine Model'),
        ),
    ]
