# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-03 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_auto_20200403_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='alarm_system',
            field=models.BooleanField(default=False, help_text='Is an alarm system installed?', verbose_name='Alarm System'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='alarm_system_information',
            field=models.CharField(blank=True, help_text='Please provide further information about the alarm system.', max_length=80, verbose_name='Alarm System Specification'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_mail',
            field=models.EmailField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Format: '+49 541 38 05 38 100'", max_length=128),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='ap_street_nr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='authorized_person_on_site',
            field=models.CharField(blank=True, help_text='Please specify the authorized person (or company) on site', max_length=50, verbose_name='Authorized Person on site'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_mail',
            field=models.EmailField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Format: '+49 541 38 05 38 100'", max_length=128),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='co_street_nr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='commencement_current_service_contract',
            field=models.DateField(blank=True, help_text='When did your current service contract commence?', null=True, verbose_name='Commencement of current service contract'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='commercial_operator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='current_service_contract',
            field=models.CharField(blank=True, help_text='Which type of service contract do you currently use', max_length=50, verbose_name='Current service contract'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='desired_duration_service_contract',
            field=models.IntegerField(blank=True, help_text='Please provide the desired duration of the service contract in years.', null=True, verbose_name='Desired duration of service contract'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='desired_service_contract',
            field=models.CharField(blank=True, choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without Main Components', 'Full Maintenance Main Components'), ('Full Maintenance with Main Components', 'Full Maintenance with Main Components'), ('Remote Control', 'Remote Control'), ('Other', 'Other')], default='Full Maintenance with Main Components', help_text='Which type of service contract are you looking for?', max_length=50, verbose_name='Desired service contract scope'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='direct_marketer',
            field=models.CharField(blank=True, help_text='Who is the direct marketer', max_length=30, verbose_name='Direct Marketer'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='grid_operator',
            field=models.CharField(blank=True, help_text='Which company is operating the elctricity grid?', max_length=50, verbose_name='Grid operator'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='it_contact_person',
            field=models.CharField(blank=True, help_text='Who can provide detailed information about the IT infrastructure of the windfarm?', max_length=100, verbose_name='IT Contact Person'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='it_mail',
            field=models.EmailField(blank=True, max_length=80, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='it_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Format: '+49 541 38 05 38 100'", max_length=128, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='key_safe_code',
            field=models.CharField(blank=True, help_text='What is the code to unlock the key safe', max_length=10, verbose_name='Key Safe Code'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='key_safe_location',
            field=models.CharField(blank=True, help_text='Where can the key safe be found', max_length=80, verbose_name='Key Safe Location'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='metering_point',
            field=models.CharField(blank=True, help_text='What is the metering point?', max_length=30, verbose_name='Metering Point'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='roadmap',
            field=models.FileField(blank=True, help_text='Please provide a file illustrating the way to get to the windfarm.', upload_to='customer_questionnaire/roadmap/', verbose_name='Roadmap'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='single_line_diagram',
            field=models.FileField(blank=True, help_text='Please provide the single line diagram of the windfarm.', upload_to='customer_questionnaire/single_line_diagram/', verbose_name='Single Line Diagram'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='substation',
            field=models.CharField(blank=True, help_text='To which substation is the windfarm connected?', max_length=50, verbose_name='Substation'),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='technical_operator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_mail',
            field=models.EmailField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Format: '+49 541 38 05 38 100'", max_length=128),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='to_street_nr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2020, 4, 3, 10, 41, 5, 741628)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='antenna',
            field=models.BooleanField(default=False, help_text='Is an antenna (mobile communications or directional radio) installed?', verbose_name='Antenna'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='antenna_type',
            field=models.CharField(blank=True, help_text='Specify the installed antenna!', max_length=40, verbose_name='Type of Antenna'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='arrester_system',
            field=models.CharField(blank=True, help_text='Specify the Arrester System!', max_length=40, verbose_name='Arrester System'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='cms_type',
            field=models.CharField(blank=True, help_text='Specify the installed CMS!', max_length=30, verbose_name='Type of CMS'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='converter_manufacturer',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the installed converter', max_length=40, verbose_name='Manufacturer of converter'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='converter_serialnr',
            field=models.CharField(blank=True, help_text='Specify the serial number of the installed converter', max_length=40, verbose_name='Serial number of converter'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='converter_type',
            field=models.CharField(blank=True, help_text='Specify the type of the installed converter', max_length=40, verbose_name='Type of converter'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='converter_year',
            field=models.IntegerField(blank=True, help_text='In which year was the converter replaced/overhauled?', null=True, verbose_name='Year of converter replacement/overhaul'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_blade_bearing_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed blade bearing inspection', null=True, verbose_name='Date of recently performed blade bearing inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_cb_inspection_machine_tower',
            field=models.DateField(blank=True, help_text='Date of recently performed condition based inspection of machine and tower', null=True, verbose_name='Date of recently performed condition based inspection of machine and tower'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_electric_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed electric inspection', null=True, verbose_name='Date of recently performed electric inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_gearbox_endoscopy',
            field=models.DateField(blank=True, help_text='Date of recently performed videoendoscopic inspection of gear box', null=True, verbose_name='Date of recently performed videoendoscopic inspection of gear box'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_5_year_maintenance',
            field=models.DateField(blank=True, help_text='Date of recently performed: 5-year-maintenance', null=True, verbose_name='Date of recently performed 5-year-maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_converter_maintenance',
            field=models.DateField(blank=True, help_text='converter maintenance', null=True, verbose_name='Date of recently performed converter maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_lattice_maintenance',
            field=models.DateField(blank=True, help_text='Date of recently performed: lattice tower maintenance', null=True, verbose_name='Date of recently performed lattice tower maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_overhaul_winch',
            field=models.DateField(blank=True, help_text='general overhaul of service lift winch', null=True, verbose_name='Date of recently performed general overhaul of service lift winch'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_recent_maintenance',
            field=models.DateField(blank=True, help_text='When was the recent maintenance performed?', null=True, verbose_name='Date of recently performed maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_of_transformer_maintenance',
            field=models.DateField(blank=True, help_text='transformer maintenance', null=True, verbose_name='Date of recently performed transformer maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_hydraulic',
            field=models.DateField(blank=True, help_text='Date of recently performed oil exchange: hydraulics', null=True, verbose_name='Date of recently performed oil exchange: hydraulics'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_main_bearing',
            field=models.DateField(blank=True, help_text='Date of recently performed oil exchange: main bearing', null=True, verbose_name='Date of recently performed oil exchange: main bearing'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_pitch_gearbox',
            field=models.DateField(blank=True, help_text='Date of recently performed oil exchange: pitch gearbox', null=True, verbose_name='Date of recently performed oil exchange: pitch gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_yaw_gearbox',
            field=models.DateField(blank=True, help_text='Date of recently performed oil exchange: yaw gearbox', null=True, verbose_name='Date of recently performed oil exchange: yaw gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_recurring_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed recurring inspection', null=True, verbose_name='Date of recently performed recurring inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_rotor_blade_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed rotor blade inspection', null=True, verbose_name='Date of recently performed rotor blade inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_safety_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed safety inspection', null=True, verbose_name='Date of recently performed safety inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_service_lift_inspection',
            field=models.DateField(blank=True, help_text='Date of recently performed service lift inspection', null=True, verbose_name='Date of recently performed service lift inspection'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_service_lift_maintenance',
            field=models.DateField(blank=True, help_text='Date of recently performed maintenance of service lift', null=True, verbose_name='Date of recently performed maintenance of service lift'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='expert_report',
            field=models.FileField(blank=True, help_text='Please provide the the recent expert report of this WEC.', upload_to='customer_questionnaire/expert_reports/', verbose_name='Expert Report'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='feed_in_tarif',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Feed-in-tarif in €/kWh', max_digits=4, null=True, verbose_name='Feed-in-tarif'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='flicker_detection_type',
            field=models.CharField(blank=True, help_text='Specify the installed flicker detection system!', max_length=30, verbose_name='Type of flicker detection system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_manufacturer',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the installed gearbox', max_length=40, verbose_name='Manufacturer of gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_serialnr',
            field=models.CharField(blank=True, help_text='Specify the serial number of the installed gearbox', max_length=40, verbose_name='Serial number of gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_type',
            field=models.CharField(blank=True, help_text='Specify the type of the installed gearbox', max_length=40, verbose_name='Type of gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_year',
            field=models.IntegerField(blank=True, help_text='In which year was the gearbox replaced/overhauled?', null=True, verbose_name='Year of gearbox replacement/overhaul'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='generator_manufacturer',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the installed generator', max_length=40, verbose_name='Manufacturer of generator'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='generator_serialnr',
            field=models.CharField(blank=True, help_text='Specify the serial number of the installed generator', max_length=40, verbose_name='Serial number of generator'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='generator_type',
            field=models.CharField(blank=True, help_text='Specify the type of the installed generator', max_length=40, verbose_name='Type of generator'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='generator_year',
            field=models.IntegerField(blank=True, help_text='In which year was the generator replaced/overhauled?', null=True, verbose_name='Year of generator replacement/overhaul'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='ice_sensor_type',
            field=models.CharField(blank=True, help_text='Specify the installed Ice Sensor System!', max_length=30, verbose_name='Type of Ice sensor'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='ladder',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the ladder!', max_length=40, verbose_name='Ladder'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Specify the latitude of the location of the WEC.', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Specify the longitude of the location of the WEC.', null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_manufacturer',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the installed obsatcle light system!', max_length=30, verbose_name='Manufacturer of obstacle light system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], default='Night', help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, verbose_name='Type of obstacle light system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_de',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], default='Night', help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, null=True, verbose_name='Type of obstacle light system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_en',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], default='Night', help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, null=True, verbose_name='Type of obstacle light system'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_hydraulic',
            field=models.CharField(blank=True, help_text='Specify the oil type recently used for the hydraulics', max_length=40, verbose_name='Recently used oil type for hydraulics'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_main_bearing',
            field=models.CharField(blank=True, help_text='Specify the oil type recently used for the main bearing', max_length=40, verbose_name='Recently used oil type for main bearing'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_pitch_gearbox',
            field=models.CharField(blank=True, help_text='Specify the oil type recently used for the pitch gearbox', max_length=40, verbose_name='Recently used oil type for pitch gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_yaw_gearbox',
            field=models.CharField(blank=True, help_text='Specify the oil type recently used for the yaw gearbox', max_length=40, verbose_name='Recently used oil type for yaw gearbox'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='output_power',
            field=models.IntegerField(blank=True, help_text='Provide the WEC output power in kW', null=True, verbose_name='Output power'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='recent_maintenance',
            field=models.CharField(blank=True, help_text='Specify the type of the recently performed maintenance (Type2/3/4)!', max_length=40, verbose_name='Recently performed maintenance'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_manufacturer',
            field=models.CharField(blank=True, help_text='Specify the manufacturer of the installed rotor blades', max_length=40, verbose_name='Manufacturer of rotor blades'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_serialnr',
            field=models.CharField(blank=True, help_text='Specify the serial number of the installed rotor blades', max_length=40, verbose_name='Serial number of rotor blades'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_type',
            field=models.CharField(blank=True, help_text='Specify the type of the installed rotor blades', max_length=40, verbose_name='Type of rotor blades'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_year',
            field=models.IntegerField(blank=True, help_text='In which year were the rotor blades replaced/overhauled?', null=True, verbose_name='Year of rotor blade replacement/overhaul'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='sdl',
            field=models.BooleanField(default=False, help_text="Relevant for WEC in Germany: Has the WEC been enabled for 'Systemdienstleistung'", verbose_name='SDL'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='service_lift',
            field=models.BooleanField(default=False, help_text='Is a service lift installed?', verbose_name='Service Lift'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='service_lift_type',
            field=models.CharField(blank=True, help_text='Specify the Service Lift!', max_length=30, verbose_name='Type of Service Lift'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_1',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Production of: last year in kWh', max_digits=9, null=True, verbose_name='Yearly Production 1'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_2',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='two years ago in kWh', max_digits=9, null=True, verbose_name='Yearly Production 2'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_3',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='three years ago in kWh', max_digits=9, null=True, verbose_name='Yearly Production 3'),
        ),
    ]
