# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-06 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_auto_20200403_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='changed_by',
        ),
    ]
