# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-22 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0115_remove_project_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionnaire',
            name='direct_marketing',
            field=models.BooleanField(default=False, help_text='Is the windfarm inegrated into direct marketing of its production?', verbose_name='Direct marketing'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='amount_wec',
            field=models.PositiveIntegerField(help_text='Please provide the number of concerned turbines', null=True, verbose_name='Amount of Turbines'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='bank_institute',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Institute'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='city',
            field=models.CharField(blank=True, help_text='Please specify the city where the wind farm is located', max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='commercial_operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='Commercial Operator'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_company',
            field=models.CharField(help_text='Please specify the company you work for', max_length=80, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_name',
            field=models.CharField(help_text='Please enter your first and last name', max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_position',
            field=models.CharField(blank=True, help_text='Please specify your position within your company', max_length=80, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contractual_partner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contractual Partner'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='desired_duration_service_contract',
            field=models.PositiveIntegerField(blank=True, help_text='Please provide the desired duration of the service contract in years.', null=True, verbose_name='Desired duration of service contract'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='desired_service_contract',
            field=models.CharField(blank=True, choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without Main Components', 'Full Maintenance Main Components'), ('Full Maintenance with Main Components', 'Full Maintenance with Main Components'), ('Remote Control', 'Remote Control'), ('Other', 'Other')], help_text='Which type of service contract are you looking for?', max_length=50, verbose_name='Desired service contract scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='invoice_recipient',
            field=models.CharField(blank=True, max_length=50, verbose_name='Invoice Recipient'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='location_details',
            field=models.CharField(blank=True, help_text='You can provide additional information', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shipping Company'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='street_nr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='technical_operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='Technical Operator'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='wind_farm_name',
            field=models.CharField(help_text='If multiple names exists, please provide them all', max_length=80, verbose_name='Wind Farm Name'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='amount',
            field=models.PositiveIntegerField(blank=True, help_text='Amount of turbines included in this project.', null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_number_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='number',
            field=models.CharField(db_index=True, help_text='Offer Number generated automatically to ensure its uniqueness.', max_length=50, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='sales_manager',
            field=models.ForeignKey(blank=True, help_text='Who is the responsible Sales Manager?', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sales Manager'),
        ),
        migrations.AlterField(
            model_name='offernumber',
            name='wind_farm',
            field=models.CharField(blank=True, help_text='Specify the wind farm which belongs to this offer number', max_length=50, null=True, verbose_name='Wind Farm'),
        ),
        migrations.AlterField(
            model_name='poolproject',
            name='projects',
            field=models.ManyToManyField(db_index=True, help_text='Assign all projects related to this Pool Project', related_name='pool_projects', to='projects.Project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='poolproject',
            name='request_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was the first contact established?', null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='poolproject',
            name='sales_manager',
            field=models.ForeignKey(help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, related_name='pool_sales_manager', to=settings.AUTH_USER_MODEL, verbose_name='Sales manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='awarding_reason',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Contract Design', 'Contract Design'), ('Experience with DWT', 'Experience with DWT'), ('Readiness', 'Readiness'), ('Regional Structures', 'Regional Structures'), ('Political Decision', 'Political Decision'), ('Liability', 'Liability')], help_text='Which reason lead to the awarding of the contract?', max_length=30, null=True, verbose_name='Awarding Reason'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(choices=[('New Contract', 'New Contract'), ('Extension', 'Extension'), ('Upgrade', 'Upgrade'), ('Downgrade', 'Downgrade')], default='New Contract', max_length=30, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_signature',
            field=models.DateField(blank=True, help_text='When is the contract intended to be signed?', null=True, verbose_name='Contract Signature'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without MC', 'Full Maintenance without MC'), ('Full Maintenance with MC', 'Full Maintenance with MC'), ('Remote Control', 'Remote Control'), ('Spare Parts', 'Spare Parts'), ('Technical Operation', 'Technical Operation'), ('Foundation works', 'Foundation works'), ('Subsea Foundation and Seabed works', 'Subsea Foundation and Seabed works'), ('Offshore sub station service', 'Offshore sub station service'), ('BNK', 'BNK'), ('Other', 'Other')], default='Contract Overview', max_length=30, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gearbox_endoscopy',
            field=models.BooleanField(default=False, verbose_name='Videoendoscopic gearbox inspection'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer_number',
            field=models.ForeignKey(blank=True, help_text='Offer Number to establish a connection to written offers', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.OfferNumber', verbose_name='Offer Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='State the average yearly remuneration per WTG', null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was the first contact established?', null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rotor',
            field=models.BooleanField(default=False, verbose_name='Rotor blade inspection'),
        ),
        migrations.AlterField(
            model_name='project',
            name='run_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Runtime [years]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_manager',
            field=models.ForeignKey(help_text='Who is the responsible Sales Manager?', on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager', to=settings.AUTH_USER_MODEL, verbose_name='Sales Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_operation',
            field=models.DateField(blank=True, help_text='What is the intended contract commencement date?', null=True, verbose_name='Operation Start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender',
            field=models.BooleanField(default=False, help_text='Is this project part of a tender?', verbose_name='Tender'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zop',
            field=models.BooleanField(default=False, verbose_name='Condition based inspection'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(help_text='The reminder is going to pop up on this specified date, which has to be in the future.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the converter replaced/overhauled?', null=True, verbose_name='Year of converter replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='customer_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.CustomerQuestionnaire', verbose_name='Customer Questionnaire'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the gearbox replaced/overhauled?', null=True, verbose_name='Year of gearbox replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the generator replaced/overhauled?', null=True, verbose_name='Year of generator replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='hub_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hub height in meters', max_digits=5, null=True, verbose_name='Hub Height'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Choose the manufacturer of the turbine', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, verbose_name='Type of obstacle light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_de',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, null=True, verbose_name='Type of obstacle light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_en',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Specify the installed obsatcle light system and its manufacturer!', max_length=20, null=True, verbose_name='Type of obstacle light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year were the rotor blades replaced/overhauled?', null=True, verbose_name='Year of rotor blade replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Type of tower', max_length=20, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_de',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Type of tower', max_length=20, null=True, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_en',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Type of tower', max_length=20, null=True, verbose_name='Type of tower'),
        ),
    ]
