# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0116_auto_20200422_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_yaw_bearing',
            field=models.DateField(blank=True, help_text='When was the last oil exchange on the yaw bearing performed?', null=True, verbose_name='Date of recently performed oil exchange: yaw bearing'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_yaw_bearing',
            field=models.CharField(blank=True, help_text='Please state the name of the used type of oil for the yaw bearing.', max_length=40, verbose_name='Used oil type for yaw bearing'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='alarm_system',
            field=models.BooleanField(default=False, help_text='Is an alarm system installed? If yes, kindly check the box.', verbose_name='Alarm System'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='amount_wec',
            field=models.PositiveIntegerField(help_text='Please state the number of relevant WTG.', null=True, verbose_name='Amount of Turbines'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ap_city',
            field=models.CharField(blank=True, help_text='Please enter city of your local hand.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ap_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address of your local hand.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ap_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter the phone number of your local hand in the format '+49 541 38 05 38 100'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ap_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of your local hand.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ap_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of your local hand.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='authorized_person_on_site',
            field=models.CharField(blank=True, help_text='Please indicate (if existing) the complete name of a local hand for the windfarm. ', max_length=50, verbose_name='Local hand on site'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='bank_institute',
            field=models.CharField(blank=True, help_text='Please indicate the name of the relevant bank.', max_length=50, verbose_name='Bank Institute'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='bic',
            field=models.CharField(blank=True, help_text='Please indicate BIC', max_length=11),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='city',
            field=models.CharField(blank=True, help_text='Please name the village where the wind farm is located.', max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_city',
            field=models.CharField(blank=True, help_text='Please enter city of your commercial operations manager.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_contact_person',
            field=models.CharField(blank=True, help_text='Please indicate first and last name of  the commercial operations manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address of the commercial operations manager.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter the phone number of the commercial operations manager in the format '+49 541 38 05 38 100'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of your commercial operations manager.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='co_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of your commercial operations manager.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='commencement_current_service_contract',
            field=models.DateField(blank=True, help_text='Kindly provide the expiry date of your current contract.', null=True, verbose_name='Expiry of current service contract'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='commercial_operator',
            field=models.CharField(blank=True, help_text='Please enter the full company name of the commercial operations manager.', max_length=50, verbose_name='Commercial Operator'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_company',
            field=models.CharField(help_text='Please enter name of your employer including type of business i.e. ltd. or GmbH & Co. KG', max_length=80, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_mail',
            field=models.EmailField(help_text='Please enter your mail address', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_name',
            field=models.CharField(help_text='Please enter your first and last name.', max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contact_position',
            field=models.CharField(blank=True, help_text='Please indicate your position in the company.', max_length=80, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='contractual_partner',
            field=models.CharField(blank=True, help_text='Please indicate the complete name of the contractual partner.', max_length=50, verbose_name='Contractual Partner'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_city',
            field=models.CharField(blank=True, help_text='Please enter city of the contractual partner.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_contact_person',
            field=models.CharField(blank=True, help_text='Please indicate first and last name of a contact person.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_legal_form',
            field=models.CharField(blank=True, help_text='Please indicate the correct type of business of the contractual partner i.e. ltd. or GmbH & Co. KG.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address of the contact person', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter the phone number of the contact person in the format '+49 541 38 05 38 100'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of the contractual partner.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='cp_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of the contractual partner.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='current_service_contract',
            field=models.CharField(blank=True, help_text='Kindly let us know about your current type of service agreement (full maintenance, time and material or others).', max_length=50, verbose_name='Current service contract'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='desired_duration_service_contract',
            field=models.PositiveIntegerField(blank=True, help_text='Please indicate the desired duration of the service contract in years.', null=True, verbose_name='Desired duration of service contract'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='desired_service_contract',
            field=models.CharField(blank=True, choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without Main Components', 'Full Maintenance Main Components'), ('Full Maintenance with Main Components', 'Full Maintenance with Main Components'), ('Remote Control', 'Remote Control'), ('Other', 'Other')], help_text='Kindly indicate your desired scope of services.', max_length=50, verbose_name='Desired service contract scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='direct_marketer',
            field=models.CharField(blank=True, help_text='Please give the name of the company.', max_length=30, verbose_name='Direct Marketer'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='direct_marketing',
            field=models.BooleanField(default=False, help_text='Is the wind farm in direct marketing?', verbose_name='Direct marketing'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='grid_operator',
            field=models.CharField(blank=True, help_text='Which company operates the electricity grid? Please give name of the utility.', max_length=50, verbose_name='Grid operator'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='iban',
            field=models.CharField(blank=True, help_text='Please indicate IBAN.', max_length=34),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='invoice_recipient',
            field=models.CharField(blank=True, help_text='Please enter the full company name of the invoice receipient.', max_length=50, verbose_name='Invoice Recipient'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_city',
            field=models.CharField(blank=True, help_text='Please enter city of the invoice recipient.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_contact_person',
            field=models.CharField(blank=True, help_text='Please indicate first and last name of a contact person at the financial department of the invoice receipient.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_invoice_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address to which invoices shall be send in future.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address of the contact person at the financial department.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter the phone number of the contact person in the format '+49 541 38 05 38 100'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of the invoice recipient.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of the invoice recipient.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='ir_tax_id',
            field=models.CharField(blank=True, help_text='Please indicate value added tax ID number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='it_contact_person',
            field=models.CharField(blank=True, help_text='Please give name and contact details of a person who could provide detailed information about the IT infrastructure of the wind farm.', max_length=100, verbose_name='IT Contact Person'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='it_mail',
            field=models.EmailField(blank=True, help_text='Please enter the mail address of a person who could provide detailed information about the IT infrastructure of the wind farm.', max_length=80, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='it_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please enter the phone number of a person who could provide detailed information about the IT infrastructure of the wind farm.', max_length=128, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='key_safe_code',
            field=models.CharField(blank=True, help_text='If a key safe is installed kindly povide access code.', max_length=10, verbose_name='Key Safe Code'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='key_safe_location',
            field=models.CharField(blank=True, help_text='Where can the key for the WTG be found?', max_length=80, verbose_name='Key Safe Location'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='location_details',
            field=models.CharField(blank=True, help_text='Here you can enter additional information on the location of the wind farm.', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='metering_point',
            field=models.CharField(blank=True, help_text='Please state the meter number of the 4-quadrant meter.', max_length=30, verbose_name='Metering Point'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Please enter the postal code of the location of the wind farm', max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='roadmap',
            field=models.FileField(blank=True, help_text='Kindly upload a map showing the location and access to the wind farm.', upload_to='customer_questionnaire/roadmap/', verbose_name='Roadmap'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_city',
            field=models.CharField(blank=True, help_text='Please enter city of the shipping address.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_company',
            field=models.CharField(blank=True, help_text='Please enter the full (company) name of the shipping recipient.', max_length=50, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_information',
            field=models.CharField(blank=True, help_text='Here you can enter additional information on the shipping address.', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of the shipping address.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='sa_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of the shipping address.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please choose your prefered scope.', max_length=30, verbose_name='Desired Scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope_de',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please choose your prefered scope.', max_length=30, null=True, verbose_name='Desired Scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='scope_en',
            field=models.CharField(choices=[('Service Contract', 'Service Contract'), ('Technical Operations Contract', 'Technical Operations Contract'), ('Commisioned Work', 'Commisioned Work'), ('Request for Material', 'Request for Material'), ('Support Contract', 'Support Contract')], default='Service Contract', help_text='Please choose your prefered scope.', max_length=30, null=True, verbose_name='Desired Scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='single_line_diagram',
            field=models.FileField(blank=True, help_text='Kindly upload a single line diagram of the wind farm.', upload_to='customer_questionnaire/single_line_diagram/', verbose_name='Single Line Diagram'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='street_nr',
            field=models.CharField(blank=True, help_text='Please enter the street and if possible the house number of the location of the wind farm', max_length=50, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='substation',
            field=models.CharField(blank=True, help_text='To which grid station is the wind farm connected? - Kindly indicate the name of the grid station.', max_length=50, verbose_name='Substation'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='technical_operator',
            field=models.CharField(blank=True, help_text='Please enter the full company name of the technical operations manager.', max_length=50, verbose_name='Technical Operator'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_city',
            field=models.CharField(blank=True, help_text='Please enter city of your technical operations manager.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_contact_person',
            field=models.CharField(blank=True, help_text='Please indicate first and last name of a contact person at the technical operations manager.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_mail',
            field=models.EmailField(blank=True, help_text='Please enter the email address of the technical operations manager.', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter the phone number of the contact person in the format '+49 541 38 05 38 100'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_postal_code',
            field=models.CharField(blank=True, help_text='Please enter post code of your technical operations manager.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='to_street_nr',
            field=models.CharField(blank=True, help_text='Please enter street name and number of the technical operations manager.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='wind_farm_name',
            field=models.CharField(help_text='If several wind farm names exist, please name all of them.', max_length=80, verbose_name='Wind Farm Name'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='antenna',
            field=models.BooleanField(default=False, help_text='Is an antenna (mobile communication or radio relay) installed? If yes, kindly check the box.', verbose_name='Antenna'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='antenna_type',
            field=models.CharField(blank=True, help_text='Please specify the type of the installed antenna. ', max_length=40, verbose_name='Type of Antenna'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='arrester_system',
            field=models.CharField(blank=True, help_text='Please specify the arrester system.', max_length=40, verbose_name='Arrester System'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='cms',
            field=models.BooleanField(default=False, help_text='Is a condition monitoring system installed? If yes, kindly check the box.'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='cms_type',
            field=models.CharField(blank=True, help_text='Please enter the type of the installed CMS.', max_length=30, verbose_name='Type of CMS'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='comissioning',
            field=models.DateField(blank=True, help_text='Kindly provide the commissioning date of the individual WTG.', null=True, verbose_name='Date of comissioning'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='control_system',
            field=models.CharField(blank=True, help_text='Kindly state which type of  turbine controller is installed.', max_length=30, verbose_name='Control system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_manufacturer',
            field=models.CharField(blank=True, help_text='Please specify the manufacturer of the installed converter.', max_length=40, verbose_name='Manufacturer of converter'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_serialnr',
            field=models.CharField(blank=True, help_text='Please enter the serial number of the installed converter.', max_length=40, verbose_name='Serial number of converter'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_type',
            field=models.CharField(blank=True, help_text='Please specify the type of the installed converter.', max_length=40, verbose_name='Type of converter'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_year',
            field=models.PositiveIntegerField(blank=True, help_text="In which year was the converterr replaced/reconditioned? Please choose 'no' or the year of replacement.", null=True, verbose_name='Year of converter replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_blade_bearing_inspection',
            field=models.DateField(blank=True, help_text='When was the last rotor blade bearing inspection performed?', null=True, verbose_name='Date of recently performed blade bearing inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_cb_inspection_machine_tower',
            field=models.DateField(blank=True, help_text='When was the last condition-based inspection of machine and tower performed?', null=True, verbose_name='Date of recently performed condition based inspection of machine and tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_electric_inspection',
            field=models.DateField(blank=True, help_text='When was the last electrical inspection carried out?', null=True, verbose_name='Date of recently performed electric inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_gearbox_endoscopy',
            field=models.DateField(blank=True, help_text='When was the last video endoscopy of the gearbox performed?', null=True, verbose_name='Date of recently performed videoendoscopic inspection of gear box'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_5_year_maintenance',
            field=models.DateField(blank=True, help_text='When was the last 5-year maintenance performed?', null=True, verbose_name='Date of recently performed 5-year-maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_converter_maintenance',
            field=models.DateField(blank=True, help_text='When was the last converter maintenance  performed?', null=True, verbose_name='Date of recently performed converter maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_lattice_maintenance',
            field=models.DateField(blank=True, help_text='If applicalble: When was the last lattice tower maintenance.', null=True, verbose_name='Date of recently performed lattice tower maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_overhaul_winch',
            field=models.DateField(blank=True, help_text='When was the general inspection of the Service Lift Winch carried out?', null=True, verbose_name='Date of recently performed general overhaul of service lift winch'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_recent_maintenance',
            field=models.DateField(blank=True, help_text='When was the last maintenance performed?', null=True, verbose_name='Date of recently performed maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_of_transformer_maintenance',
            field=models.DateField(blank=True, help_text='When was the last transformer maintenance performed?', null=True, verbose_name='Date of recently performed transformer maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_hydraulic',
            field=models.DateField(blank=True, help_text='When was the last oil exchange of hydraulic System performed?', null=True, verbose_name='Date of recently performed oil exchange: hydraulics'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_main_bearing',
            field=models.DateField(blank=True, help_text='When was the last oil/grease exchange on the main bearing performed?', null=True, verbose_name='Date of recently performed oil exchange: main bearing'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_pitch_gearbox',
            field=models.DateField(blank=True, help_text='When was the last oil exchange on the pitch gear performed?', null=True, verbose_name='Date of recently performed oil exchange: pitch gearbox'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_oil_exchange_yaw_gearbox',
            field=models.DateField(blank=True, help_text='When was the last oil exchange on the yaw gear performed?', null=True, verbose_name='Date of recently performed oil exchange: yaw gear'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_recurring_inspection',
            field=models.DateField(blank=True, help_text='When was the last routine inspection performed?', null=True, verbose_name='Date of recently performed routine inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_rotor_blade_inspection',
            field=models.DateField(blank=True, help_text='When was the last Inspection of the rotor blades performed?', null=True, verbose_name='Date of recently performed rotor blade inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_safety_inspection',
            field=models.DateField(blank=True, help_text='When was the last safety inspection carried out?', null=True, verbose_name='Date of recently performed safety inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_service_lift_inspection',
            field=models.DateField(blank=True, help_text='When was the last service lift inspection performed?', null=True, verbose_name='Date of recently performed service lift inspection'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='date_service_lift_maintenance',
            field=models.DateField(blank=True, help_text='When was the last service lift maintenance performed?', null=True, verbose_name='Date of recently performed maintenance of service lift'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='expert_report',
            field=models.FileField(blank=True, help_text='Kindly upload the current expert inspection report of the WTG', upload_to='customer_questionnaire/expert_reports/', verbose_name='Expert Report'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='feed_in_tarif',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Please state the feed-in tariff in €/kWh.', max_digits=4, null=True, verbose_name='Feed-in-tarif'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='flicker_detection',
            field=models.BooleanField(default=False, help_text='Is a shadow casting detection system installed? If yes, kindly check the box.', verbose_name='Shadow casting detection system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='flicker_detection_type',
            field=models.CharField(blank=True, help_text='Please indicate the type of shadow casting detection system.', max_length=30, verbose_name='Type of shadow casting detection system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_manufacturer',
            field=models.CharField(blank=True, help_text='Please specify the manufacturer of the gear box.', max_length=40, verbose_name='Manufacturer of gearbox'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_serialnr',
            field=models.CharField(blank=True, help_text='Please enter the serial number of the installed gear unit.', max_length=40, verbose_name='Serial number of gearbox'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_type',
            field=models.CharField(blank=True, help_text='Please indicate the installed type of gear box.', max_length=40, verbose_name='Type of gearbox'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_year',
            field=models.PositiveIntegerField(blank=True, help_text="In which year was the gearbox replaced/reconditioned? Please choose 'no' or the year of replacement.", null=True, verbose_name='Year of gearbox replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_manufacturer',
            field=models.CharField(blank=True, help_text='Please specify the manufacturer of the installed generator.', max_length=40, verbose_name='Manufacturer of generator'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_serialnr',
            field=models.CharField(blank=True, help_text='Please enter the serial number of the installed generator.', max_length=40, verbose_name='Serial number of generator'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_type',
            field=models.CharField(blank=True, help_text='Please specify the type of the installed generator.', max_length=40, verbose_name='Type of generator'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_year',
            field=models.PositiveIntegerField(blank=True, help_text="In which year was the generator replaced/reconditioned? Please choose 'no' or the year of replacement.", null=True, verbose_name='Year of generator replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='hub_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Please provide the hub height in meters.', max_digits=5, null=True, verbose_name='Hub Height'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='ice_sensor',
            field=models.BooleanField(default=False, help_text='Is an ice detection system installed? If yes, kindly check the box.', verbose_name='Ice detection system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='ice_sensor_type',
            field=models.CharField(blank=True, help_text='Please enter the type of the installed ice detection system.', max_length=30, verbose_name='Type of ice detection system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='ladder',
            field=models.CharField(blank=True, help_text='Please indicate the manufacturer of the ladder.', max_length=40, verbose_name='Ladder'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Please provide geo coodinates for latitude of the WTG accordingly.', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Please provide geo coodinates for longitude of the WTG accordingly.', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Please select the manufacturer of the turbine.', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_manufacturer',
            field=models.CharField(blank=True, help_text='Please specify the manufacturer of the installed obstruction light.', max_length=30, verbose_name='Manufacturer of obstruction light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_system',
            field=models.BooleanField(default=False, help_text='Is a obstruction light installed? If yes, kindly check the box.', verbose_name='Obstruction light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Please indicate the type of the installed obstruction lights system.', max_length=20, verbose_name='Type of obstruction light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_de',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Please indicate the type of the installed obstruction lights system.', max_length=20, null=True, verbose_name='Type of obstruction light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_en',
            field=models.CharField(blank=True, choices=[('Day/Night', 'Day/Night'), ('Night', 'Night')], help_text='Please indicate the type of the installed obstruction lights system.', max_length=20, null=True, verbose_name='Type of obstruction light system'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_hydraulic',
            field=models.CharField(blank=True, help_text='Please state the name of the used type of oil for the hydraulic system.', max_length=40, verbose_name='Used oil type for hydraulics'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_main_bearing',
            field=models.CharField(blank=True, help_text='Please state the name of the used oil/grease type for the main bearing.', max_length=40, verbose_name='Used oil type for main bearing'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_pitch_gearbox',
            field=models.CharField(blank=True, help_text='Please state the name of the used type of oil for the pitch gear.', max_length=40, verbose_name='Used oil type for pitch gear'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='oil_type_yaw_gearbox',
            field=models.CharField(blank=True, help_text='Please state the name of the used type of oil for the yaw gear.', max_length=40, verbose_name='Used oil type for yaw gear'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='output_power',
            field=models.IntegerField(blank=True, help_text='Please enter the WTG capacity in kW.', null=True, verbose_name='Output power'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='recent_maintenance',
            field=models.CharField(blank=True, help_text='Specify the last performed type of maintenance  (type 2/3/4).', max_length=40, verbose_name='Recently performed maintenance'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_manufacturer',
            field=models.CharField(blank=True, help_text='Please indicate the manufacturer of the installed rotor blades.', max_length=40, verbose_name='Manufacturer of rotor blades'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_serialnr',
            field=models.CharField(blank=True, help_text='Please enter the serial number of the installed rotor blades.', max_length=40, verbose_name='Serial number of rotor blades'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_type',
            field=models.CharField(blank=True, help_text='Please indicate the type of the installed rotor blades.', max_length=40, verbose_name='Type of rotor blades'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_year',
            field=models.PositiveIntegerField(blank=True, help_text="In which year were the rotor blades replaced/reconditioned? Please choose 'no' or the year of replacement.", null=True, verbose_name='Year of rotor blade replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='sdl',
            field=models.BooleanField(default=False, help_text="Only for WTG in Germany: Has the WTG been approved for 'System Dienstleistungs Bonus - SDL '?", verbose_name='SDL'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='service_lift',
            field=models.BooleanField(default=False, help_text='Is a service lift installed? If yes, kindly check the box.', verbose_name='Service Lift'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='service_lift_type',
            field=models.CharField(blank=True, help_text='Kindly indicate which type of service lift is installed.', max_length=30, verbose_name='Type of Service Lift'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Please specify the tower type.', max_length=20, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_de',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Please specify the tower type.', max_length=20, null=True, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_en',
            field=models.CharField(blank=True, choices=[('Lattice Tower', 'Lattice Tower'), ('Tubular Tower', 'Tubular Tower')], help_text='Please specify the tower type.', max_length=20, null=True, verbose_name='Type of tower'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='turbine_id',
            field=models.CharField(blank=True, help_text='Please indicate the serial number of the WTG.', max_length=25, verbose_name='Turbine ID'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='turbine_model',
            field=models.ForeignKey(blank=True, help_text='Please indicate the type of WTG (e.g. V90, N117 or 3.4M).', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Turbine Model'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_1',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kindly provide the production data of the last year in kWh.', max_digits=9, null=True, verbose_name='Yearly Production 1'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_2',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kindly provide the production data two years ago in kWh.', max_digits=9, null=True, verbose_name='Yearly Production 2'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='yearly_production_3',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kindly provide the production data three years ago in kWh.', max_digits=9, null=True, verbose_name='Yearly Production 3'),
        ),
    ]
