# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_auto_20200424_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquestionnaire',
            name='scope_de',
        ),
        migrations.RemoveField(
            model_name='customerquestionnaire',
            name='scope_en',
        ),
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_de',
        ),
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='obstacle_light_type_en',
        ),
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_de',
        ),
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='tower_type_en',
        ),
        migrations.AddField(
            model_name='customerquestionnaire',
            name='confirm_data_security',
            field=models.BooleanField(default=False),
        ),
    ]
