# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0118_auto_20200429_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='converter_exchange',
            field=models.BooleanField(default=False, help_text='Has the converter already been replaced or overhauled?'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_exchange',
            field=models.BooleanField(default=False, help_text='Has the gear unit already been replaced or overhauled?'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='generator_exchange',
            field=models.BooleanField(default=False, help_text='Has the generator already been replaced or overhauled?'),
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_exchange',
            field=models.BooleanField(default=False, help_text='Have the rotor blades already been replaced or overhauled?'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='desired_service_contract',
            field=models.CharField(blank=True, choices=[('Basic Maintenance', 'Basic Maintenance'), ('Full Maintenance without Main Components', 'Full Maintenance with Main Components'), ('Full Maintenance with Main Components', 'Full Maintenance with Main Components'), ('Remote Control', 'Remote Control'), ('Other', 'Other')], help_text='Kindly indicate your desired scope of services.', max_length=50, verbose_name='Desired service contract scope'),
        ),
        migrations.AlterField(
            model_name='customerquestionnaire',
            name='direct_marketing',
            field=models.BooleanField(default=False, help_text='Is the wind farm in direct marketing? If yes, kindly check the box.', verbose_name='Direct marketing'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='converter_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the converterr replaced/reconditioned?', null=True, verbose_name='Year of converter replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='gearbox_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the gearbox replaced/reconditioned?', null=True, verbose_name='Year of gearbox replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='generator_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year was the generator replaced/reconditioned?', null=True, verbose_name='Year of generator replacement/overhaul'),
        ),
        migrations.AlterField(
            model_name='turbine_customerquestionnaire',
            name='rotor_blade_year',
            field=models.PositiveIntegerField(blank=True, help_text='In which year were the rotor blades replaced/reconditioned?', null=True, verbose_name='Year of rotor blade replacement/overhaul'),
        ),
    ]
