# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-30 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0120_auto_20200429_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, help_text='Kindly upload the current expert inspection report of the WTG', upload_to='customer_questionnaire/expert_reports/', verbose_name='Expert Report')),
            ],
        ),
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='expert_report',
        ),
        migrations.AddField(
            model_name='turbine_customerquestionnaire',
            name='expert_report',
            field=models.ManyToManyField(to='projects.Expert_Report'),
        ),
    ]
