# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_auto_20200430_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine_customerquestionnaire',
            name='expert_report',
        ),
        migrations.AddField(
            model_name='expert_report',
            name='turbine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.Turbine_CustomerQuestionnaire', verbose_name='Turbine'),
            preserve_default=False,
        ),
    ]
