# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-20 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0126_customerquestionnaire_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology_responsible',
            field=models.ManyToManyField(blank=True, help_text='Who is the technology responsible?', null=True, related_name='technology_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Technology Responsible'),
        ),
    ]
