# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-22 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0127_project_technology_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology_responsible',
            field=models.ManyToManyField(blank=True, help_text='Who is the technology responsible?', related_name='technology_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Technology Responsible'),
        ),
    ]
