# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0129_graduatedprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatedprice',
            name='duration',
        ),
        migrations.AddField(
            model_name='graduatedprice',
            name='end_year',
            field=models.DateField(help_text="State the graduated price's end year", null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='graduatedprice',
            name='start_year',
            field=models.DateField(help_text="State the graduated price's start year", null=True, verbose_name='Start year'),
        ),
        migrations.AlterField(
            model_name='graduatedprice',
            name='yearly_price',
            field=models.PositiveIntegerField(help_text='State the yearly remuneration per WTG', null=True, verbose_name='Yearly Price'),
        ),
    ]
