# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0131_auto_20200612_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatedprice',
            name='id_in_project',
            field=models.PositiveIntegerField(help_text='Graduated Price ID. Unique for each GP in a given Project', null=True, verbose_name='Graduated Price ID'),
        ),
    ]
