# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-10 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0134_auto_20200714_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('risk_description', models.TextField(verbose_name='Risk description')),
                ('resolution_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Resovled')),
                ('resolution', models.TextField(verbose_name='Cause of resolution')),
                ('resolved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_notice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_notice_resolved_by', to=settings.AUTH_USER_MODEL, verbose_name='Resolved by')),
            ],
        ),
    ]
