# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-14 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0135_risknotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risknotice',
            options={'permissions': (('can_resolve_risk_notice', 'Can resolve Risk Notices.'),)},
        ),
    ]
