# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0007_remove_wec_typ_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wind_Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wec_types/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_turbines', models.IntegerField(blank=True, default=2, null=True)),
                ('hub_height', models.IntegerField(blank=True, default=100, null=True)),
                ('commisioning', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, default=47.58, max_digits=5, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=16.62, max_digits=5, null=True)),
                ('developer', models.CharField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('offshore', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='NO', max_length=20)),
                ('status', models.CharField(choices=[('in production', 'PRO'), ('under construction', 'CON'), ('planned', 'PLA'), ('dismantled', 'DIS')], default='NO', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='wind_farms.Country')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='polls.Manufacturer')),
                ('wec_typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wec_types', to='polls.WEC_Typ')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='wind_farm',
            index_together=set([('id', 'slug')]),
        ),
    ]
