# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wind_farm',
            name='image',
        ),
    ]
