# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0002_remove_wind_farm_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wind_Farm',
            new_name='WindFarm',
        ),
    ]
