# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0003_auto_20170720_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='wec_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ'),
        ),
    ]
