# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0005_auto_20170720_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='amount_turbines',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Amount of turbines'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='status',
            field=models.CharField(choices=[('PRO', 'in production'), ('under construction', 'CON'), ('planned', 'PLA'), ('dismantled', 'DIS')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='wec_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Model'),
        ),
    ]
