# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0006_auto_20170723_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='offshore',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='status',
            field=models.CharField(choices=[('PRO', 'in production'), ('CON', 'under construction'), ('PLA', 'planned'), ('DIS', 'dismantled')], default='in production', max_length=50),
        ),
    ]
