# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0008_auto_20170724_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 7, 27, 11, 704982), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 7, 27, 11, 705044), null=True),
        ),
    ]
