# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0009_auto_20170728_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 7, 29, 20, 484082, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 7, 29, 20, 484141, tzinfo=utc), null=True),
        ),
    ]
