# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0012_auto_20170728_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 19, 54, 35, 502926, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 19, 54, 35, 502988, tzinfo=utc), null=True),
        ),
    ]
