# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20170801_0627'),
        ('wind_farms', '0017_auto_20170801_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windfarm',
            name='com_operator',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='com_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_operators', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 1, 7, 9, 50, 13359, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.RemoveField(
            model_name='windfarm',
            name='developer',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 1, 7, 9, 50, 13402, tzinfo=utc), null=True),
        ),
        migrations.RemoveField(
            model_name='windfarm',
            name='owner',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='player.Player'),
        ),
        migrations.RemoveField(
            model_name='windfarm',
            name='service',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='player.Player'),
        ),
        migrations.RemoveField(
            model_name='windfarm',
            name='tec_operator',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='tec_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tec_operators', to='player.Player'),
        ),
    ]
