# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0018_auto_20170801_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 6, 26, 26, 775710, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 6, 26, 26, 775767, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=47.58, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=16.62, max_digits=8, null=True),
        ),
    ]
