# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0020_auto_20170802_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windfarm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='com_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_operators', to='player.Player', verbose_name='Commercial operator'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 12, 15, 35, 778048, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 12, 15, 35, 778133, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='tec_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tec_operators', to='player.Player', verbose_name='Technical operator'),
        ),
    ]
