# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0021_auto_20170802_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windfarm',
            name='position',
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 12, 20, 30, 407416, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 2, 12, 20, 30, 407462, tzinfo=utc), null=True),
        ),
    ]
