# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20170801_0627'),
        ('wind_farms', '0022_auto_20170802_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 9, 57, 21, 701339, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.RemoveField(
            model_name='windfarm',
            name='developer',
        ),
        migrations.AddField(
            model_name='windfarm',
            name='developer',
            field=models.ManyToManyField(to='player.Player'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 9, 57, 21, 701386, tzinfo=utc), null=True),
        ),
    ]
