# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20170801_0627'),
        ('wind_farms', '0023_auto_20170807_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 12, 2, 21, 3148, tzinfo=utc), null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 12, 2, 21, 3203, tzinfo=utc), null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 12, 2, 21, 4287, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 7, 12, 2, 21, 4319, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='wind_farms.Contract'),
        ),
    ]
