# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0031_auto_20170816_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('commercial management', 'Commercial management'), ('technical operations', 'Technical operations'), ('service', 'Service')], default='service', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 22, 7, 56, 4, 306223, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 22, 7, 56, 4, 306191, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='com_operator',
            field=models.ManyToManyField(blank=True, null=True, related_name='com_operators', to='player.Player', verbose_name='Commercial operator'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 22, 7, 56, 4, 301775, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 22, 7, 56, 4, 301820, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='tec_operator',
            field=models.ManyToManyField(blank=True, null=True, related_name='tec_operators', to='player.Player', verbose_name='Technicial operator'),
        ),
    ]
