# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0036_auto_20170824_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='follow_up_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wind_farms.WindFarm', verbose_name='Subsequent wind farm'),
        ),
        migrations.AddField(
            model_name='windfarm',
            name='repowered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 24, 11, 14, 16, 132136, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 24, 11, 14, 16, 132100, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 24, 11, 14, 16, 127702, tzinfo=utc), null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='dismantling',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 24, 11, 14, 16, 127746, tzinfo=utc), null=True),
        ),
    ]
