# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0046_auto_20170911_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='wind_farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wind_farms.WindFarm'),
        ),
    ]
