# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0047_auto_20170911_1015'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='turbine',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='com_operator',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='service',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='tec_operator',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='wec_manufacturer',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='wec_typ',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='wind_farm',
        ),
        migrations.DeleteModel(
            name='Turbine',
        ),
    ]
