# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0050_windfarm_offshore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='offshore',
            field=models.BooleanField(default=False),
        ),
    ]
