# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0052_auto_20171024_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='wind_farms.Country'),
        ),
    ]
