# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0053_auto_20171024_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
