# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0055_windfarm_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information like: Is composed of two parts', null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Enter an approximation of the wind farm's centre", null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Enter an approximation of the wind farm's centre", null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='name',
            field=models.CharField(db_index=True, help_text="Avoid wind farm names like: 'Hörup II', 'Hörup repowering' or 'Hörup extension'", max_length=80),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='offshore',
            field=models.BooleanField(default=False, help_text='Is the wind farm built offshore?'),
        ),
    ]
