# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0056_auto_20180912_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional information like: Is composed of two parts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
