# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0058_auto_20181008_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='latitude',
            field=models.FloatField(default=49.8046937, help_text="Enter an approximation of the wind farm's centre"),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='longitude',
            field=models.FloatField(default=1.8066702, help_text="Enter an approximation of the wind farm's centre"),
        ),
    ]
