# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0060_auto_20181219_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='second_name',
            field=models.CharField(default='', help_text='In case a second name for the wind farm is known, please provide it.', max_length=80),
            preserve_default=False,
        ),
    ]
