# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0061_windfarm_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='second_name',
            field=models.CharField(blank=True, help_text='In case a second name for the wind farm is known, please provide it.', max_length=80),
        ),
    ]
