# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0063_auto_20190110_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='country',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='wind_farms.Country'),
        ),
    ]
