# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0064_auto_20190208_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='city',
            field=models.CharField(blank=True, help_text='Please specify ONE city', max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='country',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='wind_farms.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information like: Is composed of two parts', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='second_name',
            field=models.CharField(blank=True, help_text='In case a second name for the wind farm is known, please provide it.', max_length=80, verbose_name='Second Name'),
        ),
    ]
