# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0065_auto_20200320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarm',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated'),
        ),
    ]
