# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wind_farms', '0014_auto_20170731_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('web', models.URLField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(choices=[('DEV', 'developer'), ('TEC', 'technical operation'), ('COM', 'commercial management'), ('SER', 'service'), ('OWN', 'owner')], default='owner', max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wind_farms.Country')),
            ],
        ),
    ]
