# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wind_farms.Country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sector',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DEV', 'developer'), ('TEC', 'technical operation'), ('COM', 'commercial management'), ('SER', 'service'), ('OWN', 'owner')], default='owner', max_length=30, null=True),
        ),
    ]
