# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 06:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170731_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sector',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DEV', 'developer'), ('TEC', 'technical operation'), ('COM', 'commercial management'), ('SER', 'service'), ('OWN', 'owner')], default=None, max_length=30, null=True),
        ),
    ]
