# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sector',
        ),
        migrations.AddField(
            model_name='player',
            name='sector',
            field=models.ManyToManyField(to='player.Sector'),
        ),
    ]
