# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180530_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
    ]
