# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_person_works_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='works_for',
        ),
    ]
