# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_remove_person_works_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
