# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(blank=True, to='player.Player'),
        ),
    ]
