# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20180613_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(blank=True, to='player.Player'),
        ),
    ]
