# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20180613_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(through='player.CompanyEmployee', to='player.Player'),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='player.Person'),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='employees',
            field=models.ManyToManyField(through='player.CompanyEmployee', to='player.Person'),
        ),
    ]
