# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_auto_20180613_0650'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='person',
        #    name='coorp',
        #    field=models.ManyToManyField(related_name='cooperations', through='player.CompanyEmployee', to='player.Player'),
        #),
        #migrations.AlterField(
        #    model_name='person',
        #    name='company',
        #    field=models.ManyToManyField(blank=True, to='player.Player'),
        #),
    ]
