# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_auto_20180613_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='player.Person'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coorp', to='player.Player'),
        ),
    ]
