# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_auto_20180613_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployee',
            name='person',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='player',
        ),
        migrations.RemoveField(
            model_name='person',
            name='coorp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='employees',
        ),
        migrations.DeleteModel(
            name='CompanyEmployee',
        ),
    ]
