# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_auto_20180625_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='function',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
