# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_person_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
