# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_auto_20180903_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='player',
            name='customer_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
