# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0027_auto_20180930_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wind_farms.Country'),
        ),
    ]
