# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_auto_20180930_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.CharField(blank=True, default='', help_text='Role of the employee within its company', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Enter the phone number beginning with +', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Enter the phone number beginning with +', max_length=128),
            preserve_default=False,
        ),
    ]
