# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_auto_20180930_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='customer_code',
            field=models.CharField(blank=True, help_text="Enter the customer code acc. to 'Projektübersicht'", max_length=10, null=True),
        ),
    ]
