# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0034_auto_20190110_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, help_text='Enter the postal address', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
