# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='adress',
            field=models.CharField(blank=True, help_text='Enter the postal address', max_length=100, verbose_name='Address'),
        ),
    ]
