# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0038_auto_20190307_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, help_text='First name and last name of the employee', max_length=50, verbose_name='Name'),
        ),
    ]
