# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0039_auto_20190507_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='head_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
