# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0043_auto_20200228_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_index=True, default=' ', help_text='First name of the employee', max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('divers', 'divers')], db_index=True, default='divers', help_text='Sex of the employee', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, help_text='Last name of the employee', max_length=50, verbose_name='Last Name'),
        ),
    ]
