# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wind_farms', '0066_auto_20200422_1408'),
        ('player', '0044_auto_20200714_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='wind_farms.Country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, help_text='Enter the postal address', max_length=100, verbose_name='Street and house number'),
        ),
    ]
