# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-20 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0047_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mailing_list',
            field=models.ManyToManyField(blank=True, to='player.MailingList', verbose_name='Mailing List'),
        ),
    ]
