# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20170824_1227'),
        ('turbine', '0002_auto_20170911_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('commercial management', 'Commercial management'), ('technical operations', 'Technical operations'), ('service', 'Service')], default='service', max_length=50)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbine_contract_actor', to='player.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='turbine',
            options={'ordering': ('turbine_id',)},
        ),
        migrations.RenameField(
            model_name='turbine',
            old_name='wec_nr',
            new_name='turbine_id',
        ),
        migrations.AddField(
            model_name='turbine',
            name='follow_up_wec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine', verbose_name='Subsequent Turbine'),
        ),
        migrations.AddField(
            model_name='contract',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine'),
        ),
    ]
