# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0003_auto_20170912_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['start_date']},
        ),
    ]
