# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0004_auto_20171023_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='wec_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wec_manufacturers', to='polls.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
