# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0005_auto_20171027_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='commisioning',
            field=models.DateField(blank=True, null=True, verbose_name='Commisioning date'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='dismantling',
            field=models.DateField(blank=True, null=True),
        ),
    ]
