# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0007_turbine_osm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
