# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0011_auto_20171213_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='latitude',
            field=models.FloatField(default=52.4518),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='longitude',
            field=models.FloatField(default=8.6792),
        ),
    ]
