# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0012_auto_20180426_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
