# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0013_auto_20180503_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine',
            name='wec_manufacturer',
        ),
    ]
