# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0014_remove_turbine_wec_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='wec_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Model'),
        ),
    ]
