# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0016_auto_20180704_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/%Y/%m/%d/'),
        ),
    ]
