# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0017_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rotor_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
