# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0018_contract_rotor_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='V-TB-22270-24-02-01_Vollwartungsvertrag_WP XY', max_length=100)),
                ('dwt', models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', max_length=30)),
                ('location_type', models.CharField(choices=[('External Storage', 'External Storage'), ('Engineering', 'Engineering'), ('Vehicle', 'Vehicle'), ('North-East', 'North-East'), ('North-West', 'North-West'), ('Head Quarter', 'Head Quarter'), ('South-East', 'South-East'), ('South-West', 'South-West'), ('Transfer Storage', 'Transfer Storage')], default='Vehicle', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
