# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0020_auto_20180709_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocation',
            name='postal_code',
            field=models.CharField(default='49082', max_length=20),
        ),
    ]
