# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0022_turbine_asset_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
