# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_auto_20180910_0647'),
        ('turbine', '0023_auto_20180906_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contact_com',
            field=models.ManyToManyField(blank=True, null=True, related_name='contact_com_contracts', to='player.Person', verbose_name='Contact Commercial Operations'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_contact_contracts', to='player.Person', verbose_name='Customer Contact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_tec',
            field=models.ManyToManyField(blank=True, null=True, related_name='contact_tec_contracts', to='player.Person', verbose_name='Contact Technical Operations'),
        ),
    ]
