# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0025_auto_20180910_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='additional_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='certified_body_inspection_service_lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='electrical_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='periodic_inspection_wtg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='pressure_vessels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='rotor_blade_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='safety_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='safety_repairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_lift_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='videoendoscopic_inspection_gearbox',
            field=models.BooleanField(default=False),
        ),
    ]
