# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0026_auto_20180911_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='turbines',
            field=models.ManyToManyField(db_index=True, help_text='Add all turbines included in this contract', related_name='contracted_turbines', to='turbine.Turbine', verbose_name='Turbines'),
        ),
    ]
