# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0027_auto_20180911_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='wtg_availability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Availability Guarantee for single WTG in %', max_digits=4, null=True),
        ),
    ]
