# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0028_auto_20180911_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='actor',
            field=models.ForeignKey(help_text='Enter the contractual partner', on_delete=django.db.models.deletion.CASCADE, related_name='turbine_contract_actor', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='additional_maintenance',
            field=models.BooleanField(default=False, help_text='Are additional scheduled maintenances (e.g. TypeIV) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='average_remuneration',
            field=models.DecimalField(decimal_places=2, default=35000, help_text='Enter the average remuneration per year of this contract', max_digits=8),
        ),
        migrations.AlterField(
            model_name='contract',
            name='certified_body_inspection_service_lift',
            field=models.BooleanField(default=False, help_text='Is the inspection of the service lift by a certified body (ZÜS) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_com',
            field=models.ManyToManyField(blank=True, help_text='Enter the contact person of the commercial operator', related_name='contact_com_contracts', to='player.Person', verbose_name='Contact Commercial Operations'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_customer',
            field=models.ManyToManyField(blank=True, help_text='Enter the contact person of the customer', related_name='customer_contact_contracts', to='player.Person', verbose_name='Customer Contact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_tec',
            field=models.ManyToManyField(blank=True, help_text='Enter the contact person of the technical operator', related_name='contact_tec_contracts', to='player.Person', verbose_name='Contact Technical Operations'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='electrical_inspection',
            field=models.BooleanField(default=False, help_text='Are the electrical inspection (DGUV V3) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter the effective end date of this contract', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='external_damages',
            field=models.BooleanField(default=False, help_text='Is an insurance for external damages included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='farm_availability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Availability Guarantee for the wind farm in %', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, help_text='Attach the pdf file of the contract', null=True, upload_to='contract_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='main_components',
            field=models.BooleanField(default=False, help_text='Are main components included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter a name for the contract acc. to the scheme of the placeholder', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='periodic_inspection_wtg',
            field=models.BooleanField(default=False, help_text='Are periodic inspections of the WTG (WKP) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pressure_vessels',
            field=models.BooleanField(default=False, help_text='Is the replacement of pressure vessels included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remote_control',
            field=models.BooleanField(default=False, help_text='Is remote control included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rotor_blade_inspection',
            field=models.BooleanField(default=False, help_text='Are rotor blade inspections included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rotor_excluded',
            field=models.BooleanField(default=False, help_text='Is the rotor excluded from the main components?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='safety_inspection',
            field=models.BooleanField(default=False, help_text='Is the inspection of safety equipment (PSE, fire extinguisher, etc.) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='safety_repairs',
            field=models.BooleanField(default=False, help_text='Is the repair and replacement of safety equipment (PSE, fire extinguisher, etc.) included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scheduled_maintenance',
            field=models.BooleanField(default=False, help_text='Is scheduled maintenance included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_lift_maintenance',
            field=models.BooleanField(default=False, help_text='Is service lift maintenance included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter the effective commencement date of this contract', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unscheduled_maintenance_material',
            field=models.BooleanField(default=False, help_text='Are materials for unscheduled maintenance included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unscheduled_maintenance_personnel',
            field=models.BooleanField(default=False, help_text='Is personnel for unscheduled maintenance included?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videoendoscopic_inspection_gearbox',
            field=models.BooleanField(default=False, help_text='Are videoendoscopic inspections of the gearbox included?'),
        ),
    ]
