# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0029_auto_20180911_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='asset_management',
            field=models.ManyToManyField(blank=True, help_text="Specify the company which manages the turbine's asset", related_name='wec_asset_management', to='player.Player', verbose_name='Asset Management'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='com_operator',
            field=models.ManyToManyField(blank=True, help_text='Specify the company which commercially manages the turbine', related_name='wec_com_operators', to='player.Player', verbose_name='Commercial operator'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='developer',
            field=models.ManyToManyField(blank=True, help_text='Specify the company which developed the turbine', related_name='wec_developers', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='dismantling',
            field=models.DateField(blank=True, help_text='If the turbine has been dismantled, specify the date of dismantling', null=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='follow_up_wec',
            field=models.ForeignKey(blank=True, help_text='If it has been repowered, by which turbine?', null=True, on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine', verbose_name='Subsequent Turbine'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='offshore',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='Is this turbine built offshore', max_length=50),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='osm_id',
            field=models.CharField(blank=True, help_text='Openstreetmap ID', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Specify the company which owns the turbine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wec_owners', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='repowered',
            field=models.BooleanField(default=False, help_text='If the turbine has been dismantled, has it been repowered afterwards?'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Specify the company which currently services the turbine', related_name='wec_service_providers', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='tec_operator',
            field=models.ManyToManyField(blank=True, help_text='Specify the company which technically operates the turbine', related_name='wec_tec_operators', to='player.Player', verbose_name='Technicial operator'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='turbine_id',
            field=models.CharField(db_index=True, help_text='If Turbine ID is unknown use this scheme: Windfarm01', max_length=25),
        ),
    ]
