# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0032_auto_20180912_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='average_remuneration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the average remuneration per year of this contract', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='osm_id',
            field=models.CharField(blank=True, default='', help_text='Openstreetmap ID', max_length=25),
            preserve_default=False,
        ),
    ]
