# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 12:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0033_auto_20180930_1751'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contract',
            managers=[
                ('related_windfarms', django.db.models.manager.Manager()),
            ],
        ),
    ]
