# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-15 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0034_auto_20181015_1214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contract',
            managers=[
            ],
        ),
    ]
