# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0035_auto_20181015_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', max_length=30),
        ),
    ]
