# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0036_contract_dwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='actor',
            field=models.ForeignKey(help_text='Enter the contractual partner', on_delete=django.db.models.deletion.CASCADE, related_name='turbine_contract_actor', to='player.Player', verbose_name='Contractual Partner'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTSW', 'DWTSW'), ('DWTDK', 'DWTDK')], default='DWTX', max_length=30, verbose_name='DWT Unit'),
        ),
    ]
