# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0038_auto_20181120_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='turbine_id',
            field=models.CharField(db_index=True, help_text='If Turbine ID is unknown use this scheme: <Windfarm name>01', max_length=25),
        ),
    ]
