# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0039_auto_20181122_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='turbine_id',
            field=models.CharField(db_index=True, help_text='If Turbine ID is unknown use this scheme: <Windfarm name>01. NEG turbines should be labeled by the Vestas abbreviation "V".', max_length=25),
        ),
    ]
