# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20180930_1740'),
        ('turbine', '0041_servicelocation_supported_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelocation',
            name='supported_technology',
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='supported_technology',
            field=models.ManyToManyField(to='polls.Manufacturer'),
        ),
    ]
