# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0042_auto_20181203_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='commisioning',
            field=models.DateField(blank=True, default=datetime.date(2018, 1, 1), help_text='If the exact date is unknown, use January 1st', null=True, verbose_name='Commisioning date'),
        ),
    ]
