# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0043_auto_20181217_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='commisioning',
            field=models.DateField(blank=True, help_text='If the exact date is unknown, use January 1st', null=True, verbose_name='Commisioning date'),
        ),
    ]
