# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0044_auto_20181217_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='wec_typ',
            field=models.ForeignKey(help_text='Enter the turbine type (e.g. V90) not the manufacturer (e.g. Vestas)!', on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ', verbose_name='Model'),
        ),
    ]
