# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-10 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0049_auto_20190109_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine',
            name='commisioning',
        ),
    ]
