# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0051_auto_20190110_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine',
            name='dismantling',
        ),
    ]
