# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0052_remove_turbine_dismantling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='rotor_excluded',
        ),
        migrations.AddField(
            model_name='contract',
            name='condition_based_inspection',
            field=models.BooleanField(default=False, help_text='Are condition base inspections of the WTG (ZOP) included?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='exclusions',
            field=models.CharField(blank=True, choices=[('Rotor', 'Rotor'), ('Foundation', 'Foundation'), ('Busbars', 'Busbars'), ('Obstruction Lights', 'Obstruction Lights'), ('Transmission Station', 'Transmission Station')], max_length=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_lift_repairs',
            field=models.BooleanField(default=False, help_text='Are repairs on the service lift included?'),
        ),
    ]
