# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0053_auto_20190207_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='exclusions',
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_lift_repairs',
            field=models.BooleanField(default=False, help_text='Are repairs of the service lift included?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='exclusions',
            field=models.ManyToManyField(blank=True, help_text='Which components are exluded from the scope?', to='turbine.Exclusion'),
        ),
    ]
