# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0058_auto_20190307_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Enter the date when the contract was terminated by the customer.', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Contract Design', 'Contract Design'), ('Experience with DWT', 'Experience with DWT'), ('Readiness', 'Readiness'), ('Regional Structures', 'Regional Structures'), ('Political Decision', 'Political Decision')], help_text='Which reason lead to the termination of the contract?', max_length=30, null=True),
        ),
    ]
