# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0059_auto_20190308_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('Closure of WTG / business', 'Closure of WTG / business'), ('Alteration of Contract', 'Alteration of Contract'), ('Competition', 'Competition'), ('Change of Ownership', 'Change of Ownership'), ('Breach of Agreement', 'Breach of Agreement'), ('Bankruptcy', 'Bankruptcy')], help_text='Which reason lead to the termination of the contract?', max_length=30, null=True),
        ),
    ]
