# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turbine', '0061_auto_20190322_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dwt_responsible',
            field=models.ForeignKey(blank=True, help_text='Who is the responsible Customer Relation Manager?', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
