# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0062_contract_dwt_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['start_date'], 'permissions': (('can_comment_contracts', 'Can write comments on contracts.'), ('can_view_contract_pdf', 'Can view contract pdf.'), ('can_terminate_contract', 'Can terminate contract'), ('can_create_custom_export_of_contracts', 'Can create a custom export of contracts'), ('change_dwt_responsible', 'Can change the DWT Responsible'))},
        ),
    ]
