# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0064_auto_20190709_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='availability_type',
            field=models.CharField(choices=[('time based', 'time based'), ('energy based', 'energy based')], default='time based', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTAB', 'DWTAB'), ('DWTDK', 'DWTDK')], default='DWTX', max_length=30, verbose_name='DWT Unit'),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTAB', 'DWTAB'), ('DWTDK', 'DWTDK')], default='DWTX', max_length=30),
        ),
    ]
