# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0065_auto_20190716_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='availability_type',
            field=models.CharField(blank=True, choices=[('time based', 'time based'), ('energy based', 'energy based')], max_length=20, null=True),
        ),
    ]
