# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0071_auto_20200116_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTAB', 'DWTAB'), ('DWTDK', 'DWTDK'), ('GFW', 'GFW')], default='DWTX', max_length=30, verbose_name='DWT Unit'),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='dwt',
            field=models.CharField(choices=[('DWTX', 'DWTX'), ('DWTS', 'DWTS'), ('DWTOC', 'DWTOC'), ('DWTUK', 'DWTUK'), ('DWTSARL', 'DWTSARL'), ('DWTES', 'DWTES'), ('DWTNED', 'DWTNED'), ('DWTPO', 'DWTPO'), ('DWTUS', 'DWTUS'), ('DWTAB', 'DWTAB'), ('DWTDK', 'DWTDK'), ('GFW', 'GFW')], default='DWTX', max_length=30),
        ),
    ]
