# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0074_auto_20200520_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine',
            name='under_contract_until',
            field=models.DateField(blank=True, help_text='Specify, until when the turbine is under contract', null=True, verbose_name='Under contract until'),
        ),
    ]
