# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-03 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turbine', '0075_turbine_under_contract_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_manufacturer', models.CharField(blank=True, help_text='Please enter name of the component manufacturer', max_length=100, null=True, verbose_name='Component Manufacturer')),
                ('component_type', models.CharField(help_text='Please enter the component type', max_length=50, verbose_name='Component Type')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text='Please choose a component name.', max_length=50, verbose_name='Component Name')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentTurbineRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_turbine', models.IntegerField(default=-1, help_text='Component ID. Unique for each Component in a given Turbine', verbose_name='Component ID in Turbine')),
                ('serial_nr', models.CharField(blank=True, help_text='Please enter the serial number', max_length=50, null=True, verbose_name='Serial Number')),
                ('installation_date', models.DateField(blank=True, help_text='Kindly provide the installation date of the individual WTG.', null=True, verbose_name='Installation Date')),
                ('dismantling_date', models.DateField(blank=True, help_text='Kindly provide the dismantling date of the individual WTG.', null=True, verbose_name='Dismantling Date')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Component')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='component_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.ComponentName'),
        ),
        migrations.AddField(
            model_name='component',
            name='created_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turbine',
            name='components',
            field=models.ManyToManyField(through='turbine.ComponentTurbineRelation', to='turbine.Component'),
        ),
        migrations.AlterUniqueTogether(
            name='componentturbinerelation',
            unique_together=set([('component', 'turbine', 'id_in_turbine', 'serial_nr')]),
        ),
    ]
