# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0076_auto_20200703_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine',
            name='max_component_id',
            field=models.IntegerField(default=-1, help_text='Highest Component ID.', verbose_name='Max Component ID'),
        ),
    ]
