# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0077_turbine_max_component_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentname',
            name='component_name_verbose',
            field=models.CharField(default='Component Name', help_text='Please choose a component name.', max_length=50, verbose_name='Component Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentname',
            name='component_name',
            field=models.CharField(max_length=50, verbose_name='Internal Component Name'),
        ),
    ]
