# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0079_auto_20200714_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbine',
            name='max_component_id',
        ),
        migrations.AddField(
            model_name='componentname',
            name='component_priority',
            field=models.IntegerField(default=0, help_text='Higher values mean higher priority.', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='componentname',
            name='rds_pp',
            field=models.CharField(blank=True, help_text='RDS-PP of Component.', max_length=50, null=True, verbose_name='RDS-PP'),
        ),
        migrations.AlterUniqueTogether(
            name='componentturbinerelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='componentturbinerelation',
            name='id_in_turbine',
        ),
    ]
