# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0080_auto_20200716_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, verbose_name='Attribute Name')),
                ('attribute_value', models.CharField(max_length=100, verbose_name='Attribute Value')),
                ('component_turbine_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.ComponentTurbineRelation')),
            ],
        ),
    ]
