# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-26 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0081_componentattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine',
            name='scada_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCADA #'),
        ),
    ]
