# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0082_turbine_scada_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentturbinerelation',
            name='dismantling_date',
            field=models.DateField(blank=True, help_text='Please provide the dismantling date of the component.', null=True, verbose_name='Dismantling Date'),
        ),
        migrations.AlterField(
            model_name='componentturbinerelation',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Please provide the installation date of the component', null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='scada_nr',
            field=models.IntegerField(blank=True, help_text='Specify the SCADA number to which the turbine is connected.', null=True, verbose_name='SCADA #'),
        ),
    ]
