# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0083_auto_20200806_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_manufacturer',
        ),
    ]
