# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_manufacturer_turbine_model_manufacturer'),
        ('turbine', '0084_remove_component_component_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_manufacturer',
            field=models.ForeignKey(default=400, help_text='Please enter name of the component manufacturer', on_delete=django.db.models.deletion.CASCADE, to='polls.Manufacturer', verbose_name='Component Manufacturer'),
        ),
    ]
