# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0085_component_component_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='continued_operation',
            field=models.BooleanField(default=False, help_text='Is the continued Operation included?', verbose_name='Continued Operation'),
        ),
        migrations.AddField(
            model_name='contract',
            name='lattice_tower_maintenance',
            field=models.BooleanField(default=False, help_text='Is the lattice tower maintenance (if applicable) included?', verbose_name='Lattice Tower Maintenance'),
        ),
    ]
