# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbine', '0086_auto_20200901_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('component_turbine_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.ComponentTurbineRelation')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbine.Turbine')),
            ],
        ),
    ]
