# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('polls', '0001_initial'), ('polls', '0002_auto_20170713_0800'), ('polls', '0003_auto_20170713_1334'), ('polls', '0004_auto_20170717_0838')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'manufacturers',
                'verbose_name': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='WEC_Typ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wec_types/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('output_power', models.IntegerField(blank=True, default=0, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wea_types', to='polls.Manufacturer')),
                ('cut_in', models.DecimalField(blank=True, decimal_places=2, default=3.5, max_digits=5, null=True)),
                ('cut_out', models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=5, null=True)),
                ('drive', models.CharField(choices=[('gearbox', 'GEA'), ('gearless', 'NOG')], default='GEA', max_length=20)),
                ('hub_weight_t', models.IntegerField(blank=True, default=100, null=True)),
                ('max_hub_height', models.IntegerField(blank=True, default=140, null=True)),
                ('max_rot_speed_r_m', models.DecimalField(blank=True, decimal_places=2, default=20.5, max_digits=5, null=True)),
                ('min_hub_height', models.IntegerField(blank=True, default=60, null=True)),
                ('min_rot_speed_r_m', models.DecimalField(blank=True, decimal_places=2, default=11.5, max_digits=5, null=True)),
                ('nominal_speed', models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=5, null=True)),
                ('offshore', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='NO', max_length=20)),
                ('reg', models.CharField(choices=[('pitch', 'PIT'), ('stall', 'STA')], default='PIT', max_length=20)),
                ('rotor_diameter', models.IntegerField(blank=True, default=0, null=True)),
                ('rotor_weight_t', models.IntegerField(blank=True, default=50, null=True)),
                ('tot_weight_t', models.IntegerField(blank=True, default=400, null=True)),
                ('tower_weight_t', models.IntegerField(blank=True, default=250, null=True)),
                ('wind_class', models.CharField(blank=True, default='IEC Ia', max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, default=2000, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='wec_typ',
            index_together=set([('id', 'slug')]),
        ),
    ]
