# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_compatible_to'),
        ('polls', '0004_auto_20170717_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='components',
            field=models.ManyToManyField(to='components.Component'),
        ),
    ]
