# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('components', '0003_component_compatible_to'),
        ('polls', '0005_wec_typ_components'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='wec_typ',
        #    name='components',
        #),
        migrations.AddField(
            model_name='wec_typ',
            name='components',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.Component'),
        ),
    ]
