# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170717_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wec_typ',
            name='components',
        ),
    ]
