# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_wec_typ_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='drive',
            field=models.CharField(choices=[('gearbox', 'gearbox'), ('gearless', 'gearless')], default='gearbox', max_length=20, verbose_name='Drivetrain'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='offshore',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='reg',
            field=models.CharField(choices=[('pitch', 'pitch'), ('stall', 'pitch')], default='pitch', max_length=20, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='year',
            field=models.IntegerField(blank=True, default=2000, null=True, verbose_name='First installation'),
        ),
    ]
