# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170726_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='reg',
            field=models.CharField(choices=[('pitch', 'pitch'), ('stall', 'stall')], default='pitch', max_length=20, verbose_name='Regulation'),
        ),
    ]
