# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170728_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='product_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wec_typ',
            name='still_in_production',
            field=models.BooleanField(default=False),
        ),
    ]
