# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170824_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='nr_blades',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
