# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_wec_typ_nr_blades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wec_typ',
            name='still_in_production',
        ),
        migrations.AddField(
            model_name='wec_typ',
            name='produced_until',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
