# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170824_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_y', jsonfield.fields.JSONField()),
                ('wec_typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WEC_Typ')),
            ],
        ),
    ]
