# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 07:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_powercurve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powercurve',
            name='wec_typ',
        ),
        migrations.AddField(
            model_name='wec_typ',
            name='power_curve',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PowerCurve',
        ),
    ]
