# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170828_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.5, max_digits=5, null=True, verbose_name='Cut in wind speed'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=5, null=True, verbose_name='Cut out wind speed'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='hub_weight_t',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Hub weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_hub_height',
            field=models.IntegerField(blank=True, default=140, null=True, verbose_name='Max. Hub Height'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.5, max_digits=5, null=True, verbose_name='Max. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_hub_height',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Min. Hub Height'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=11.5, max_digits=5, null=True, verbose_name='Min. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nominal_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=5, null=True, verbose_name='Nominal wind speed'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='output_power',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Output power [W]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_diameter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rotor diameter [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_weight_t',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='Rotor weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tot_weight_t',
            field=models.IntegerField(blank=True, default=400, null=True, verbose_name='Total weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tower_weight_t',
            field=models.IntegerField(blank=True, default=250, null=True, verbose_name='Tower weight [t]'),
        ),
    ]
