# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20171103_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(db_index=True, upload_to='wec_types/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
