# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20171104_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
