# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_image_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 6, 9, 39, 16, 712819, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
