# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_image_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(default='https://www.wind-turbine-models.com', max_length=200),
        ),
    ]
