# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
