# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20171113_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wec_typ',
            options={'ordering': ('-updated',)},
        ),
    ]
