# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20171113_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='osm_id',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
