# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_wec_typ_osm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wec_typ',
            name='osm_id',
        ),
    ]
