# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_wec_typ_osm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='sound_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sound level'),
        ),
    ]
