# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_wec_typ_sound_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
