# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20180222_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
