# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_wec_typ_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wec_typ',
            name='description2',
        ),
    ]
