# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_remove_wec_typ_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wec_types', to='polls.Manufacturer'),
        ),
    ]
