# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20180514_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wind_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
