# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-05 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_wind_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wec_typ',
            name='wind_class',
        ),
    ]
