# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_remove_wec_typ_wind_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='wind_clas',
            field=models.ManyToManyField(to='polls.Wind_Class'),
        ),
    ]
