# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_wec_typ_wind_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cut in wind speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cut out wind speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information', null=True),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='hub_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nacelle weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Max. Hub Height [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Min. Hub Height [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the turbine model', max_length=200),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nominal_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nominal wind speed [m/s'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='offshore',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='Is this turbine model built for offshore?', max_length=20),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='output_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Output power [kW]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='produced_until',
            field=models.IntegerField(blank=True, help_text='In which year was this turbine model built last?', null=True),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='product_web',
            field=models.URLField(blank=True, help_text='Link to more information', null=True, verbose_name='Product web page'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rotor diameter [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rotor weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='sound_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sound level [dB]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tot_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tower_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tower weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='year',
            field=models.IntegerField(blank=True, default=2000, help_text='In which year was this turbine model built first?', null=True, verbose_name='First installation'),
        ),
    ]
