# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20180912_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='output_power',
            field=models.IntegerField(blank=True, help_text='Enter rated output power in kW', null=True, verbose_name='Output power'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_diameter',
            field=models.IntegerField(blank=True, help_text='Enter rotor diameter in m', null=True, verbose_name='Rotor diameter'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='wind_clas',
            field=models.ManyToManyField(help_text='Select (multiple) wind class', to='polls.Wind_Class'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='year',
            field=models.IntegerField(blank=True, help_text='In which year was this turbine model built first?', null=True, verbose_name='First installation'),
        ),
    ]
