# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_auto_20180912_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Upload an image file (jpg or png)', null=True, upload_to='wec_types/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(help_text='State the source/owner of the image', max_length=200),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nominal_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nominal wind speed [m/s]'),
        ),
    ]
