# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20180912_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, default='', help_text='Upload an image file (jpg or png)', upload_to='wec_types/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Cut in wind speed [m/s]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Cut out wind speed [m/s]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='hub_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Nacelle weight [t]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Max. Hub Height [m]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Max. rotor speed [m/s]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Min. Hub Height [m]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Min. rotor speed [m/s]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nominal_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Nominal wind speed [m/s]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nr_blades',
            field=models.IntegerField(blank=True, default=3, verbose_name='Amount of blades'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='output_power',
            field=models.IntegerField(blank=True, default=0, help_text='Enter rated output power in kW', verbose_name='Output power'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='power_curve',
            field=jsonfield.fields.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='produced_until',
            field=models.IntegerField(blank=True, default=1900, help_text='In which year was this turbine model built last?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='product_web',
            field=models.URLField(blank=True, default='', help_text='Link to more information', verbose_name='Product web page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_diameter',
            field=models.IntegerField(blank=True, default=0, help_text='Enter rotor diameter in m', verbose_name='Rotor diameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Rotor weight [t]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='sound_level',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, verbose_name='Sound level [dB]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tot_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Total weight [t]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tower_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Tower weight [t]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='year',
            field=models.IntegerField(blank=True, default=1900, help_text='In which year was this turbine model built first?', verbose_name='First installation'),
            preserve_default=False,
        ),
    ]
