# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 16:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_auto_20180930_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='power_curve',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
