# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_auto_20180930_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cut in wind speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='cut_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cut out wind speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='hub_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nacelle weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Max. Hub Height [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='max_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_hub_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Min. Hub Height [m]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='min_rot_speed_r_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min. rotor speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nominal_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nominal wind speed [m/s]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='nr_blades',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Amount of blades'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='output_power',
            field=models.IntegerField(blank=True, help_text='Enter rated output power in kW', null=True, verbose_name='Output power'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='produced_until',
            field=models.IntegerField(blank=True, help_text='In which year was this turbine model built last?', null=True),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_diameter',
            field=models.IntegerField(blank=True, help_text='Enter rotor diameter in m', null=True, verbose_name='Rotor diameter'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='rotor_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rotor weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='sound_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sound level [dB]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tot_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='tower_weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tower weight [t]'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='year',
            field=models.IntegerField(blank=True, help_text='In which year was this turbine model built first?', null=True, verbose_name='First installation'),
        ),
    ]
