# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20190215_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wec_typ',
            name='wind_clas',
            field=models.ManyToManyField(blank=True, help_text='Select (multiple) wind class', to='polls.Wind_Class'),
        ),
    ]
