# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-27 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_wec_typ_maintenance_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wec_typ',
            options={'ordering': ('-updated',), 'permissions': (('comment', 'Can comment on turbine models'),)},
        ),
    ]
