# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_auto_20191127_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='wec_typ',
            name='technology_class',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('FL2500', 'FL2500'), ('MM', 'MM'), ('3.XM', '3.XM'), ('N60', 'N60'), ('N80/90', 'N80/90'), ('gamma', 'gamma'), ('delta', 'delta'), ('5M', '5M')], max_length=25, null=True, verbose_name='Technology Class'),
        ),
    ]
