# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_auto_20200117_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, help_text='Upload an image file (jpg or png)', upload_to='wec_types/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(help_text='State the source/owner of the image', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='maintenance_hours',
            field=models.IntegerField(blank=True, help_text='How many maintenance hours have to be substracted from the availability guarantee?', null=True, verbose_name='Maintenance Hours'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wec_types', to='polls.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='produced_until',
            field=models.IntegerField(blank=True, help_text='In which year was this turbine model built last?', null=True, verbose_name='Produced until'),
        ),
        migrations.AlterField(
            model_name='wec_typ',
            name='wind_clas',
            field=models.ManyToManyField(blank=True, help_text='Select (multiple) wind class', to='polls.Wind_Class', verbose_name='Wind Class'),
        ),
    ]
