# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0055_auto_20200228_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='turbine_model_manufacturer',
            field=models.BooleanField(default=True),
        ),
    ]
