# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='components/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('weight_t', models.IntegerField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'component_type',
                'verbose_name_plural': 'component_types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.ComponentType'),
        ),
        migrations.AlterIndexTogether(
            name='component',
            index_together=set([('id', 'slug')]),
        ),
    ]
