# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.ComponentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
