# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170713_1334'),
        ('components', '0002_auto_20170713_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='compatible_to',
            field=models.ManyToManyField(to='polls.WEC_Typ'),
        ),
    ]
