# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_compatible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='weight_t',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
