# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20170717_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='generator_type',
            field=models.CharField(choices=[('Asynchronous', 'Asyncronous'), ('Double fed induction generator', 'Double fed induction generator'), ('Seperate-exited synchronous', 'Seperate-exited synchronous'), ('Self-exited synchronous', 'Self-exited synchronous')], default='Asynchronous', max_length=20, verbose_name='Generator_type'),
        ),
        migrations.AddField(
            model_name='component',
            name='ration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='tower_type',
            field=models.CharField(choices=[('Lattice', 'Lattice'), ('Concrete', 'Concrete'), ('Hybrid', 'Hybrid'), ('Wood', 'Wood')], default='Hybrid', max_length=20, verbose_name='Tower_type'),
        ),
        migrations.AddField(
            model_name='component',
            name='voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
