# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20170829_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='ration',
            new_name='ratio',
        ),
        migrations.AddField(
            model_name='component',
            name='stages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
