# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20170829_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.ComponentType', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='weight_t',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight [t]'),
        ),
    ]
