# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20171028_1159'),
        ('components', '0008_auto_20171102_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='components/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('weight_t', models.IntegerField(blank=True, null=True, verbose_name='Weight [t]')),
                ('generator_type', models.CharField(choices=[('Asynchronous', 'Asyncronous'), ('Double fed induction generator', 'Double fed induction generator'), ('Seperate-exited synchronous', 'Seperate-exited synchronous'), ('Self-exited synchronous', 'Self-exited synchronous')], default='Asynchronous', max_length=20)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compatible_to', models.ManyToManyField(to='polls.WEC_Typ')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='components/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('weight_t', models.IntegerField(blank=True, null=True, verbose_name='Weight [t]')),
                ('tower_type', models.CharField(choices=[('Lattice', 'Lattice'), ('Concrete', 'Concrete'), ('Hybrid', 'Hybrid'), ('Wood', 'Wood')], default='Hybrid', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compatible_to', models.ManyToManyField(to='polls.WEC_Typ')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='component',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='component',
            name='compatible_to',
        ),
        migrations.RemoveField(
            model_name='component',
            name='component_type',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
        migrations.AlterIndexTogether(
            name='tower',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='generator',
            index_together=set([('id', 'slug')]),
        ),
    ]
