# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20171104_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearbox',
            name='image',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='image',
        ),
    ]
